### ISSUE TITLE
GermanizedVariationForm onUpdate handler resets variation to default values

### ISSUE THREAD

**Issue by anito** [vendidero/woocommerce-germanized#102]
Setting an individual delivery date for a variation (different from the default parent delivery time), results in flashing that value for a very short moment after which it then gets replaced by the default value (the default delivery date of the variations parent).
 
This behaviour is observed after selecting a product variation from the dropdown in variation form which seems to trigger e.g. `update_variation_values` and `found_variation` event mapped to `onUpdate` and `onFoundVariation`

The previously mentioned flashing timespan corresponds to the `setTimeout` parameter in `onUpdate` event handler. Increasing that parameter also increases the duration after which the variation value is replaced.

Deactivating (renaming) `update_variation_values` event (name) in _add-to-cart-variation.js_ seem to recover the desired behaviour for me.

UPDATE: This issue was observed only for variation products where stock quantity === 0 !!

WooCommerce Germanized 3.0.8

**Comment by vendidero** [comment]
Hi there,

thanks for reporting. Which theme are your currently using? Did you try reproducing the problem using a default theme (e.g. storefront)? The script's `onUpdate` callback checks if Woo has deactivated/disabled the add-to-cart-button to see if the variation may be disabled or not available any longer. If that is the case (the button is disabled) the `onReset` handler is called to reset the data accordingly.

Cheers

**Comment by anito** [comment]
Hi,

I’m actually using vendidero child theme. Actually a child of it, however this issue can also observed with the child deactivated using the parent vendidero theme.
Importantly to note is that the issue only effects those product variants whose stock quantity is emty (zero quantity)

I staged the shop here: staging.ha-lehmann.at <http://staging.ha-lehmann.at/>

A product sample would be here: https://staging.ha-lehmann.at/produkt/fab-defense-kpos-scout-standard/ <https://staging.ha-lehmann.at/produkt/fab-defense-kpos-scout-standard/>

The product has 4 color variants, grey, black, tan and green
Color variants grey and black are not in stock, Tan and green are
Color variants grey and black a delivery message „z.Zt. nicht lieferbar“ is defined, however it only quickly flashes and switches back to default „Sofort versandfertig. Lieferzeit ca 2-5 Werktage“ short after
Tan and green are in stock

I could you provide with an ftp account if needed

Cheers
Axel

**Comment by vendidero** [comment]
Hi Axel,

this was actually "expected" behaviour as the variation is not purchasable - in that case Germanized removes the variation data. I'll investigate that and see what we can do about it to improve compatibility with out-of-stock items. Thanks for reporting.

**Comment by anito** [comment]
Oh I see. Would be great to see this changed. Showing here the default delivery info that in most cases gives a specific delivery time like it was on stock seems kind of misleading to the customers. Thanks for your support.

Cheers

**Comment by vendidero** [comment]
Hi,

could you share your product configuration? Are you using a plugin to show out-of-stock variations in the list? Core Woo hides the variation from the list if it is out of stock..
