### ISSUE TITLE
Sendung mit Status "Entwurf" nicht dem Kunden anzeigen

### ISSUE THREAD

**Issue by dan-nkl** [vendidero/woocommerce-germanized#103]
Warum wird eine Sendung im Status "Entwurf" bereits im Kundenbereich angezeigt?

Ich kann mir nicht vorstellen, dass es in irgendeinem Fall sinnvoll sein könnte.

In unserem Workflow wird automatisch eine Sendung mit dem Status Entwurf erstellt, sobald eine Bestellung im Status "In Bearbeitung" ist. 
Dann können wir den Lieferschein unter "Sendungen" ganz einfach drucken und die Pakete packen. Gleichzeitig setzen wir erst dann die Sendung auf "In Bearbeitung" und auf "Versandt", sobald diese beim Versanddienstleister ist.

Hätte wenigstens gerne eine Option, die regelt, welchen Status eine Sendung haben muss um im Kundenbereich angezeigt zu werden! :)

**Comment by vendidero** [comment]
Hi,

stimmt, das sollte nicht sein. Welche Version von Germanized verwendest du denn? Eigentlich schließen wir Sendungen mit Status "draft" automatisch aus.

Grüße

**Comment by dan-nkl** [comment]
Version 3.0.8 und 2.0.9 Pro

**Comment by vendidero** [comment]
Hi,

alles klar. Das habe ich lokal bereits gefixt und ist für das nächste Release eingeplant. Siehe:
https://github.com/vendidero/woocommerce-germanized-shipments

Grüße
