### ISSUE TITLE
Please add a required mark to mandatory checkboxes

### ISSUE THREAD

**Issue by DalbertHab** [vendidero/woocommerce-germanized#104]
The default woocommerce terms and conditions checkbox has a required mark `*`. The ones you added do not have this mark.

Please add
```php
<?php if ($checkbox->get_is_mandatory()) : ?>
    <span class="required">*</span>
<? endif; ?>
```
to the **checkout/terms.php** and the **checkboxes/default.php** templates.

**Comment by vendidero** [comment]
Hi there,

I'm not sure whether this is necessary as many users won't like adding the asterisk as an update. Maybe it is easier to add it via the label option within the admin settings panel (if the user decides that this is necessary).

Cheers
