### ISSUE TITLE
Proper way to hide shipping notice

### ISSUE THREAD

**Issue by strarsis** [vendidero/woocommerce-germanized#105]
Some products are services, though they may still result in a shipping fee, so not showing the shipping notice for service products wouldn't be a good default behaviour.
Virtual products are a much safer candidate for not showing the shipping notice by default, 
but apparently the shipping notice is also displayed for virtual products.

What is the proper way to mark a product or product category/property as something that is not shipped, so no shipping notice is added?
The `woocommerce_gzd_display_shipping_costs_hidden_types` option, by default empty, [lists the product types to be excluded](https://github.com/vendidero/woocommerce-germanized/blob/9237d9220dc0e7a47e4978e8575cf0a8daefe69a/includes/wc-gzd-template-functions.php#L494) from this shipping notice, but I can't find anything in admin area to set this option.

**Comment by vendidero** [comment]
Hi there,

sorry for coming back to this that late. I've (re)added the option to the admin settings panel. See this commit: https://github.com/vendidero/woocommerce-germanized/commit/08ca9b341dbbee9b92d402db0219f2805098a57a

Cheers and thanks for reporting.
