### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by Zodiac1978** [vendidero/woocommerce-germanized#106]
It is problematic to split up sentences like this:
https://github.com/vendidero/woocommerce-germanized/blob/96873df59b721e3efb9a49ef600030f2febba6ac/woocommerce-germanized.php#L47

Some languages will have problems with this approach, because the order of words is different in many languages.

We also have problems with the formal version of German.

> Germanized benötigt mindestens PHP 5.6. Bitte %s deine PHP-Version.

I need to use "Bitte aktualisieren Sie Ihre PHP-Version", but I don't know if "upgrade" is used in other contexts.

The other problem is, that there is a translator comment missing which explains what %s actually is.
See: https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#descriptions

**Comment by vendidero** [comment]
Hi there,

the order of words can be easily changed within the translation as %s is used as a placeholder for the dynamic part. I'm going to check the formal string an will fix that in the next release. 

> The other problem is, that there is a translator comment missing which explains what %s actually is.

Yes it is missing. But Germanized is not really designed to be translated in multiple languages as this plugin is tightly coupled to the german market. You can of course fix theses issues by creating pull requests. Our roadmap is quite full and I guess this is a low priority issue.

Cheers

**Comment by Zodiac1978** [comment]
It is still bad practice to split things up like this:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#best-practices-for-writing-strings

If you ever use the word "upgrade" in another context you have to remember that your formal translation is translated differently. Just a heads up.

Language packs are loaded first, so I fixed it here too:
https://translate.wordpress.org/projects/wp-plugins/woocommerce-germanized/stable/de/formal/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=8567057&filters%5Btranslation_id%5D=69041097
and here:
https://translate.wordpress.org/projects/wp-plugins/woocommerce-germanized/stable/de/formal/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=8567058&filters%5Btranslation_id%5D=69041117

PR is coming soon.

**Comment by vendidero** [comment]
Hi there,

thanks for the PR. Yes, splitting is not the best option. I'll try to fix that from time to time.
