### ISSUE TITLE
Germanized hides the shipping options

### ISSUE THREAD

**Issue by xannasavin** [vendidero/woocommerce-germanized#108]
I have Germanized installed on my little shop and I noticed the following behavior:
I have two shipping options:

- pickup

-  shipping with DHL

the customer can choose from those options for every order they make.

However, as soon as Germanized is activated, the shipping options are not selectable and only the  "shipping with DHL" option is always selected.

As soon as I deactivate Germanized, I can see the options in the checkout.

Germanized activated
![with Germanized](https://user-images.githubusercontent.com/48352696/79576563-caf12200-80c3-11ea-9fa8-ca0ea0c35ee9.jpg)

Germanized deactivated (the styling get's crazy for some reason at that point)
![Kasse – Camp Schmetterling Shop - Google Chrome 2020-04-17 15 55 11](https://user-images.githubusercontent.com/48352696/79576619-de03f200-80c3-11ea-96b9-18cf835e5dd7.jpg)

**Comment by vendidero** [comment]
Hi there,

Germanized has an option (under WooCommerce > Settings > Germanized > Button-Solution > hide shipping costs during checkout) for that - you might deactivate that option to show shipping methods during checkout.

Cheers

**Comment by xannasavin** [comment]
I checked all the options - beside that point. Thanks a lot, that did the trick!
Have a great day!
