### ISSUE TITLE
Multivendor + Germanized

### ISSUE THREAD

**Issue by strarsis** [vendidero/woocommerce-germanized#109]
Are multivendor WooCommerce plugins compatible with WooCommerce Germanized?
Are the same settings used for each vendor?

**Comment by vendidero** [comment]
Hi there,

no, there is no explicit compatibility integrated in Germanized for those plugins.
Multi-vendor-shops are very complex and might need some manual adjustments to enable them for the german market. You might of course ask the developers of those particular plugins whether they've tested their plugin with Germanized or not.

Cheers

**Comment by strarsis** [comment]
@vendidero: In this case it would be the Dokan plugin for multivendor.

**Comment by vendidero** [comment]
I've recently heard of some problems related to dokan and Germanized. See:
https://wordpress.org/support/topic/fatal-error-mit-dokan/

But anyway - Germanized does not add explicit support to handle multiple vendors - you might need to implement compatibility via hooks and filters yourself. And please check with a lawyer as these multi-vendors shops are really complex.

Cheers
