### ISSUE TITLE
Versandkosten und mehrere Umsatzsteuer-Sätze: Verhältnis Netto statt Brutto

### ISSUE THREAD

**Issue by the-infinity** [vendidero/woocommerce-germanized#112]
WooCommerce Germanized berechnet die Versandkosten im Verhältnis der Brutto-Werte der im Warenkorb enthaltenen Produkte, siehe https://github.com/vendidero/woocommerce-germanized/blob/master/includes/admin/class-wc-gzd-admin-order.php#L60 . Dies ist zufolge mehrerer Dokumente zu diesem Thema leider falsch, maßgeblich sind die Netto-Verhältnisse.

**Comment by vendidero** [comment]
Hi,

danke für deinen Einwand. Kannst du deine Quellen zu diesem Thema offenlegen? Dann werde ich mir das genauer ansehen und ggfs. die Implementierung anpassen.

Grüße

**Comment by the-infinity** [comment]
Moin, moin,

erstmal war die Quelle ein intern meckernder Steuerberater. Aber wenn man ein bisschen googled, findet man dazu auch noch ein paar weitere Quellen:
> https://blog.taxdoo.com/umsatzsteuer-versandkosten-nebenleistungen/
> https://marketpress.de/dokumentation/german-market/steuerberechnung-bei-nebenleistungen/

Wobei es vermutlich spannend wäre, da eine definitive Aussage zu bekommen. Ich wüsste nur nicht woher. Aber ich finde zumindest keine Quelle dafür, die explizit schreibt, dass das Verhältnis brutto sein sollte.

Beste Grüße,
Ernesto

**Comment by vendidero** [comment]
Hi Ernesto,

alles klar, danke für die Quelle. Ich werde das prüfen und fixen.
