### ISSUE TITLE
Why isn't the GTIN field synced into different translations?

### ISSUE THREAD

**Issue by MarekEureka** [vendidero/woocommerce-germanized#118]
Hi,

i like this plugin a lot and run it in a multilingual (WPML) woocommerce setup. We would like to use the GTIN field provided in the product settings. As far as i could figure out, this GTIN field (name _ts_grin_) is provided by woocommerce germanized. However, we noticed, that this field is set to "translate" which means, that we have to enter the GTIN in every language. For me, it is not obvious, why one would like to have different GTINs for the same product in different translations. I thought it would be more reasonable to have the GTIN configured with the "Copy" option in WPML.

However, when I checked the translation options, changing the translation method of the field "_ts_gtin" is disabled.
![Screenshot from 2020-10-02 18-24-50](https://user-images.githubusercontent.com/48926925/94946573-a4da0580-04dc-11eb-83be-42789a039752.png)
Could anybody explain to me why this is deactivated? Maybe there are good reasons to not have GTIN synced automatically, then please tell me. Otherwise, I would propose setting _ts_gtin to "copy" option in WPML.

Thanks!

**Comment by vendidero** [comment]
Hi there,

by default we've set that field to be translatable (to allow merchants to use different GTIN per language). I've just changed that to `copy-once` to copy the field by default but allow changing the value afterwards. 

Cheers
