### ISSUE TITLE
Mögliche Löschung von Shop-Manager in "WC_GZD_Customer_Helper::account_cleanup()"

### ISSUE THREAD

**Issue by jaylinski** [vendidero/woocommerce-germanized#119]
Hallo!

wenn ein Administrator oder Shop-Manager die User-Rolle "Kunde" hat, kann es in der `WC_GZD_Customer_Helper::account_cleanup()`-Funktion dazu kommen, dass dieser User gelöscht wird.

Es sollte meiner Meinung nach in `WC_GZD_Customer_Helper::account_cleanup()` ein Check eingebaut werden, ob es sich bei dem User nicht um einen Admin oder Shop-Manager handelt:

```php
		$user_query = new WP_User_Query(
			array(
				'role'       => $roles,
                                'role__not_in' => ['administrator', 'shop_manager'], // Fail safe
				'date_query' => array(
					array(
						'before'    => $registered_before,
						'inclusive' => true,
					)
				),
				'meta_query' => array(
					array(
						'key'     => '_woocommerce_activation',
						'compare' => 'EXISTS',
					),
				),
			)
		);
```
Dadurch, dass in meinem Shop ein Shop-Manager auch die Rolle `customer` hatte, aber nie "aktiviert" wurde, wurden einige, vom User angelegte Seiten, gelöscht. Der User blieb interessanterweise erhalten, vermutlich wegen eines timeouts im cronjob.

**Comment by vendidero** [comment]
Hi,

ja, das klingt sinnvoll - wobei das wirklich nur ein sehr kleines "Randproblem" sein dürfte (nichtsdestotrotz sollte es verhindert werden), da das nur dann auftritt, wenn der Admin sich ursprünglich via Frontend als Customer registriert hat. Erstellst du dazu einen Pull Request?

Grüße
