### ISSUE TITLE
Please move translations to transiflex

### ISSUE THREAD

**Issue by jnachtigall** [vendidero/woocommerce-germanized#12]
It would be cool if you could move the translations to transiflex. That's also where the WooCommerce and with it the WooCommerce translators community reside.

I just found 2, 3 minor translation issues and it would be easier to keep this plugin's translations and WC in sync if both would be on transiflex (because transiflex has a "translation memory")

**Comment by vendidero** [comment]
Hi,

think that would overshoot the mark a little. WC Germanized is still a pretty small project in comparison to WC. You may use GPL Plugins to help you while translating such as CodeStyle Localization etc.
And btw transifex seems to be proprietary and liable to pay costs (at least after a 30 day period), another reason to not move translation to them :)

**Comment by jnachtigall** [comment]
ok, up to you ;) I'll send you a po file with minor corrections later

Transiflex has the same business modell as github: Free for FOSS, pay for proprietary software.

**Comment by vendidero** [comment]
Had to search a little on their website to find that notice regarding OSS :) I'll have a look at it..
