### ISSUE TITLE
Hide digital downloads checkbox on checkout page for vouchers

### ISSUE THREAD

**Issue by strarsis** [vendidero/woocommerce-germanized#123]
Vouchers (that can be downloaded as PDF after buying them) are digital files, but they aren't the actual product and represent a real world service. Those voucher products are also "downloadable" and this seems to trigger the Digital downloads related checkbox on the checkout page. Ad this isn't necessary for vouchers, I would like to skip/hide this checkbox when only voucher products are to be bought. Can I control this somehow?

**Comment by vendidero** [comment]
Hi there,

I'll guess you could have a look at the following filter/functionality to adjust showing/hiding the digital checkbox:
https://github.com/vendidero/woocommerce-germanized/blob/master/includes/wc-gzd-product-functions.php#L151

Cheers

**Comment by strarsis** [comment]
Alright, the issue was that I misunderstood the concept of downloadable/digital products versus a PDF voucher product.
Downloadable products have a list of files that can be downloaded after purchase.
However, the PDF Voucher product already handles the downloading/sending of the PDF containing the voucher.
So the Downloadable option is not needed and should be turned off for these PDF voucher products.
