### ISSUE TITLE
Rechnungsdaten über REST-API löschen

### ISSUE THREAD

**Issue by Babelfisch** [vendidero/woocommerce-germanized#124]
Da WooCommerce ja extrem viele Daten erzeugt und bspw. in `wp_postmeta` schnell mal einige Millionen Datensätze drin sind, lösche ich regelmäßig alte Bestellungen über die REST-API von WC.

Mir ist dabei gerade aufgefallen, dass eine ganze Menge Datenmüll zurückbleibt. So gibt es einen Datensatz in `wp_post` mit dem `post_type`=`invoice` und ’zig `wp_postmeta` wie `_invoice_address` usw. Das kommt doch sicherlich von Germanized (Pro) oder?

Ist es möglich, dass sich Germanized in die REST-API einklinkt und seine Daten sauber mit löscht? Ansonsten wird das ziemlich aufwändig und lässt sich nur über eine direkt Datenbankverbindung realisieren.

**Comment by Babelfisch** [comment]
Nachtrag: Auch wenn man direkt über das Backend von WooCommerce Bestellungen löscht, bleiben die Einträge in der Datenbank erhalten. Das Problem beschränkt sich also nicht nur auf die REST-API.

**Comment by vendidero** [comment]
Hi,

du scheint offenbar noch unsere Pro Version in v2 (statt v3) zu nutzen. Grundsätzlich ist es nicht vorgesehen Rechnungen (automatisch) zu löschen nur weil Bestellungen gelöscht wurden. Die Buchhaltungsdaten werden auch bei gelöschten Bestellungen weiterhin benötigt. Das wird also als Feature nicht in Frage kommen. Bitte wende dich generell zu Support zur Pro-Version an unser Help Desk: https://vendidero.de/dashboard/help-desk

Grüße
