### ISSUE TITLE
Rechnung generieren, wenn Anzahl keine ganze Zahl ist

### ISSUE THREAD

**Issue by Friedel-Castor** [vendidero/woocommerce-germanized#125]
Hallo liebes Germanized Team,

ich habe aktuell Probleme Rechnungen zu generieren, wenn die Anzahl eines Artikels keine ganze Zahl ist. Die Tabelle in der generierten Rechnung sieht dann wie folgt aus: 

![Bildschirmfoto von 2021-01-02 01-15-22](https://user-images.githubusercontent.com/11500437/103448554-6d295800-4c9b-11eb-9c20-ea38d2d0c2b3.png)

Der Gesamtpreis stimmt zwar soweit aber die Anzahl und Einzelpreis sind offensichtlich nicht korrekt (Anzahl hätte 0,5 und Einzelpreis 16,00€ sein sollen).

Diese Funktion ist für uns sehr wichtig, da wir auch Meterware verkaufen, die in 0,5er Schritten bestellt werden kann. 

Ich Danke für eure Zeit und wünsche ein schönes neues Jahr.

Gruß
Andreas

**Comment by vendidero** [comment]
Hi Andreas,

bitte nutze für Support-Anfragen zu unserer Pro-Version unser Help Desk:
https://vendidero.de/dashboard/help-desk

Dort helfen wir dir gern weiter. Aktuell werden von unserem Buchhaltungstool Dezimalzahlen nicht unterstützt.

Grüße
