### ISSUE TITLE
woocommerce-germanized(-pro) - warenkorbkurzbeschreibung wird nur bei manueller mail übers admin-backed versanst

### ISSUE THREAD

**Issue by iq0n** [vendidero/woocommerce-germanized#127]
Germanized Pro bietet die Option an, die Warenkorbkurzbeschreibung in der Email-Benachrichtung "Bestellung erhalten / Zahlung erhalten / Rechnung" mitzusenden. Dieses Verhalten kann ich reproduzieren, indem ich im Backend bei einer Bestellung die Mails manuell auslöse. Allerdings würde ich mir wünschen, dass dieses Verhalten automatisch vollzogen wird.

Ich habe mittlerweile schon mehrere Ansätze auch über Hooks versucht und den originalen Quellcode editiert, allerdings würde ich mir wünschen so nah wie möglich am Standard, hinsichtlich weiterer Updates, zu bleiben.
Existiert hierfür ein Code-Snippet oder habe ich etwas falsch konfiguriert beziehungsweise übersehen?

Vielen Dank im Voraus!

**Comment by vendidero** [comment]
Hi,

das ist ein Feature von Germanized, nicht von Germanized Pro. Die Beschreibung wird per Hook in die Email eingefügt, s.h.: https://github.com/vendidero/woocommerce-germanized/blob/master/includes/class-wc-gzd-emails.php#L932

Bestenfalls deaktivierst du mal alle Plugins bis auf Woo und Germanized und aktivierst ein Standard-Theme. Lässt sich das dann noch reproduzieren?

**Comment by iq0n** [comment]
Hi, 

danke dir für deine schnelle Rückmeldung. Entschuldige die Vermischung der beiden Plugins! :-)

Hiermit konnte ich **meine** Problemstellung lösen:

`add_action( 'woocommerce_email_order_details', 'woocommerce_email_order_details_add_gzd_product_item_short_descp', 10, 4 );

function woocommerce_email_order_details_add_gzd_product_item_short_descp( $order, $sent_to_admin, $plain_text, $email ) {
	add_filter( 'woocommerce_order_item_name', 'wc_gzd_cart_product_item_desc', wc_gzd_get_hook_priority( 'email_product_item_desc' ), 2 );
}`

Allerdings habe ich festgestellt, dass die Aktion/Mail "Rechnungsmail / Bestelldetails senden", die manuell über das Admin Backend verschickt wird (und auch den GZD code für die product_item_desc enthält), sich von der automatisch versandten Mail unterscheidet.
Dieses Verhalten fiel mir durch Zufall auf, da ich in WC den Mailbetreff auf DEV (in der Entwicklungsumgebung) abgeändert habe und die Mail aus dem Backend diesen Betreff ignoriert.
Eventuell auch nicht Problem dieses Plugins sondern ein generelles WC Issue?

Ich bedanke mich auf jeden Fall für das Aufzeigen der richtigen Stelle in deinem Quellcode!

**Comment by vendidero** [comment]
Ich denke eher (wie oben angedeutet), dass das ein Plugin-Konflikt bzw. Theme-Konflikt ist. Bist du mal so vorgegangen?

> Bestenfalls deaktivierst du mal alle Plugins bis auf Woo und Germanized und aktivierst ein Standard-Theme. Lässt sich das dann noch reproduzieren?

**Comment by iq0n** [comment]
Nein, leider aufgrund von Zeitmangel noch nicht. 
Ich werde dir allerdings eine Rückmeldung geben, sobald ich das ausführlich getestet habe.

Schönes Wochenende!

**Comment by iq0n** [comment]
So, das hat mir keine Ruhe gelassen:

Immernoch keine Warenkorbkurzbeschreibung in einer der Mails.

Allerdings hat sich meine Problemstellung durch deinen Code lösen lassen. Nachhaltiger wäre natürlich, wenn es mit einem Update in den nächsten Monaten gefixt werden würde.


**PHP:** 
PHP-Version: 7.3.26

**Theme:**
Name: Storefront
Version: 3.4.0

**Plugins (alle aktuell):**
Vendidero Helper |   | von Vendidero – 1.3.0
WooCommerce Admin |   | von WooCommerce – 1.9.0
WooCommerce Stripe-Gateway |   | von WooCommerce – 4.8.0
Germanized für WooCommerce Pro |   | von vendidero – 3.1.4
Germanized für WooCommerce |   | von vendidero – 3.3.6
WooCommerce |   | von Automattic – 4.9.2
WP Mail SMTP |   | von WPForms – 2.5.1

**### Germanized ###**

WC GZD Version: 3.3.6
WC GZD Database Version: 3.3.6
Small Business: –
Default Delivery Time: XXX

Checkout Fallback: –

### Taxes ###

Split Tax: 
Split Tax: 
Virtual VAT: –
Tax Rate Name Collision: –
VAT Table Check: 

### Legal Pages ###

XXX1: 
XXX2: 
XXX3: 
XXX4: 
XXX5: 
XXX6: 

### Compatibility ###


### Templates ###

Overrides: –
Overrides: –
Overrides: –

**Comment by vendidero** [comment]
Habe es gerade mit Germanized in der neuesten Version samt Woo in der neuesten Version getestet und die WK-Beschreibung wird einwandfrei angefügt an alle Mails. Hast du es mal ohne Stripe über ein herkömmliches Gateway getestet?
Geht es dir um die Bestellbenachrichtigung? Testweise ein Standard-Theme aktiviert?

**Comment by vendidero** [comment]
Habe das nun speziell für Stripe (ggfs. auch andere Gateways) angepasst. Bei meinen Tests klappt es darüber auch mit Stripe: https://github.com/vendidero/woocommerce-germanized/commit/335d93fcbc9687506cf2e717be7734fd6af3a231

Grüße

**Comment by iq0n** [comment]
Hi,

ich kam leider bisher nicht daz. Gerade konnte ich allerdings feststellen, dass es an Stripe liegt. Mit Paypal hatte ich soeben keine Probleme.
Hast Du entsprechend ein neues Update veröffentlich?

**Comment by vendidero** [comment]
Hi,

nein, das ist noch nicht im neuesten Update enthalten. Kommt aber dann in das nächste.

Grüße
