### ISSUE TITLE
Remove (page builder) shortcodes in emails

### ISSUE THREAD

**Issue by Zodiac1978** [vendidero/woocommerce-germanized#128]
I added the "Impressum" (legal advice) to all client faced emails, but if I made the website with Divi and used the Divi builder for the page the mail contains all the divi builder shortcodes. I had no luck in removing them.

Any chance to get this fixed by Germanized or a hint how to do this with a filter myself?

Thanks in advance!

All the best
Torsten

**Comment by vendidero** [comment]
Hi Torsten,

you might want to use the separate email text option which is added on your edit page page as a meta box. You might even want to hook into the attachment logic and remove your shortcodes (divi) accordingly. E.g.:

`add_action( 'woocommerce_germanized_attach_email_footer', 'my_child_remove_custom_shortcodes', 20 );

function my_child_remove_custom_shortcodes() {
   // Remove all your divi shortcodes via `remove_shortcode` function
}`

Cheers

**Comment by Zodiac1978** [comment]
Hi @vendidero 

the problem is that `remove_shortcode` only unregisters the shortcode function, so the shortcode text itself is still there and that's the whole issue: showing the shortcode in the mail is what I need to prevent.

`strip_shortcodes` *is* removing the shortcode completely, but it is removing the content for containing shortcodes, like `[shortcode]Content[/shortcode]`, so that the page wouldn't show, because it would be filtered, as the divi shortcodes are all containing shortcodes.

**Comment by Zodiac1978** [comment]
I got a solution.

We can replace the shortcode callback function with our own and just return the unmodified content. We just need to run the shortcodes because they are nested. And I just use the basic variant with section, row, column, text. If more modules are used on the page, this needs to be added.

```
/**
 * Just return the content
 *
 * @param  [string] $atts    Unused attributes.
 * @param  [string] $content Submitted content.
 * @return [string]          Unmodified content with shortcodes because of nested shortcodes.
 */
function divi_remove_shortcodes( $atts, $content ) {
	return do_shortcode( $content );
}

/**
 * Unregisters divi shortcodes and re-adds with only content.
 */
function my_child_remove_custom_shortcodes() {

	remove_shortcode( 'et_pb_section' );
	remove_shortcode( 'et_pb_row' );
	remove_shortcode( 'et_pb_column' );
	remove_shortcode( 'et_pb_text' );

	add_shortcode( 'et_pb_section', 'divi_remove_shortcodes' );
	add_shortcode( 'et_pb_row', 'divi_remove_shortcodes' );
	add_shortcode( 'et_pb_column', 'divi_remove_shortcodes' );
	add_shortcode( 'et_pb_text', 'divi_remove_shortcodes' );
}
add_action( 'woocommerce_germanized_attach_email_footer', 'my_child_remove_custom_shortcodes', 20 );

```

**Comment by Zodiac1978** [comment]
> separate email text option which is added on your edit page page as a meta box

Couldn't find such a metabox. On which page exactly? Within WP? Divi? Any hints? Screenshots?

**Comment by vendidero** [comment]
Hi there,

thank you for your snippets. Might help other divi users too. That's one reason why pagebuilders are not really a great solution for creating content.

See the screenshot showing the edit page for my terms page (does only show up on your legal pages). You might need to explicitly enable the meta box via the display options.

<img width="1440" alt="Bildschirmfoto 2021-02-08 um 12 17 42" src="https://user-images.githubusercontent.com/8328938/107212779-c0639880-6a07-11eb-8bda-1875651e5b15.png">

Cheers

**Comment by Zodiac1978** [comment]
Thanks for the screenshot! Missed this totally (looked at a complete different position 😆)

Now I have two ways of fixing this. Thanks!
