### ISSUE TITLE
Please minify css and js files

### ISSUE THREAD

**Issue by jnachtigall** [vendidero/woocommerce-germanized#13]
I saw that woocommerce-germanized/assets/css/woocommerce-gzd-layout.css?ver=1.2.3 comes unminified. Could you please add minification using cssmin or [grunt-contrib-cssmin](https://github.com/gruntjs/grunt-contrib-cssmin). For both it is possible to have a `sourceMap` option.

Does also hold true for the other files in https://github.com/vendidero/woocommerce-germanized/tree/master/assets/css

gzd is the only plugin I use, that does not use minification currently.

For JS, e.g. assets/js/add-to-cart-variation.js you might want to use https://github.com/mishoo/UglifyJS2 or https://github.com/gruntjs/grunt-contrib-uglify (again: there is a `sourceMap` option here, if you want to be able to debug also on production servers)

If you want to set it up properly (takes more time at first, but pays of very soon) you might want to have a look at how WC itself does it: https://github.com/woothemes/woocommerce/blob/master/Gruntfile.js

**Comment by vendidero** [comment]
That's already on our roadmap.. Will be fixed asap..
