### ISSUE TITLE
Baue Rechnung/Lieferschein Vorlage mit visuellen Editor, schaut bei Versand ganz anders aus!

### ISSUE THREAD

**Issue by popedcorrn** [vendidero/woocommerce-germanized#130]
Ich hab im visuellen Editor eine Rechnungs-Vorlage erstellt, wenn ich aus Vorschau klicke, sieht die Rechnung ganz anders aus, auch wenn ich sie per Mail gesendet bekomme.

Selbes Problem tritt auch bei der vorgefertigten Vorlage auf (Siehe Screenshots)

**Hier wie's im visuellen Editor ausschaut:**
![Visueller Editor](https://user-images.githubusercontent.com/79857424/109518596-abc86c80-7aaa-11eb-819b-1a636c6e2862.JPG)

**Und hier wie dann die Rechnung als Mail ausschaut:**
![Vorschau](https://user-images.githubusercontent.com/79857424/109518598-ac610300-7aaa-11eb-9359-890bb37d8d78.JPG)

**Comment by vendidero** [comment]
Hi,

das ist offenbar ein Problem mit unserer Pro-Version (ich gehe davon aus, dass irgendeine Erweiterung/Server-Einstellung die CSS-Datei blockiert, sodass sie beim Rendern nicht geladen werden kann). Bitte wende dich dazu an unser Help Desk:
https://vendidero.de/dashboard/help-desk

Dort helfen wir dir dazu gern weiter.

Grüße
