### ISSUE TITLE
Anrede: Sehr geehrte(r)

### ISSUE THREAD

**Issue by strarsis** [vendidero/woocommerce-germanized#138]
Es würde den E-Mail-Text verbessern, wenn Germanized einen Platzhalter für `geehrte`/`geehrter` anbieten könnte,
was die meisten Anwendungsfälle abdecken sollte. Zurzeit wird - auch bei bekannter Anrede - `geehrte(r)` verwendet.

Außerdem sollte bei unbekannter/ungesetzter Anrede ein generischerer Anrede-Text verwendet werden können, 
z.B. `Sehr geehrter Kunde,`. Damit wird eine etwas flapsig wirkende Anrede vermieden, z.B. `Sehr geehrte(r) Mustermann`.

**Comment by vendidero** [comment]
Ich denke das greift etwas zu spezifisch in den Anwendungsfall ein. Germanized bietet hier nur eine einfache Umsetzung an - wenn du eine umfangreiche Lösung mit individuellen Kundenansprachen benötigst, solltest du per Filter eingreifen: https://github.com/vendidero/woocommerce-germanized/blob/master/includes/class-wc-gzd-emails.php#L326

oder ein Email-Customizer-Plugin verwenden bzw. die Woo-Email-Templates in deinem Child-Theme überschreiben.
