### ISSUE TITLE
Deutsche Post Versandettikett 

### ISSUE THREAD

**Issue by HendrikMennen** [vendidero/woocommerce-germanized#139]
Hallo,
Ich habe bemerkt, dass es nicht möglich ist ein Versandlabel zu generieren und dies einfach auf einem DINA4 bogen zu positionieren. Entweder der weiße Rand müsste verschwinden, sodass man in Adobe Acrobat Reader die position einstellen kann oder man bräuchte eine Funktion um die X und Y Achse schon vor dem generieren einstellen zu können.

**Comment by vendidero** [comment]
Hi,

doch, das ist durchaus möglich. Schau dir mal die Einstellungen unter Germanized > Versanddienstleister > Deutsche Post > Labels an. Dort kannst du die Druckposition X, Y-Achse anpassen.

Grüße

**Comment by HendrikMennen** [comment]
![image](https://user-images.githubusercontent.com/25281882/126786083-b0f76aab-0b26-458b-a061-03b72e950baa.png)
Ja das habe ich gesehen. Dennoch ist es recht umständlich wenn ich vor jedem label generieren immer in die Einstellungen gehen muss. Wäre es nicht besser diese Einstellung in dem Label kaufen dialog anzuzeigen?

**Comment by vendidero** [comment]
Bislang ist das nicht möglich - wir haben das aber bereits auf der Roadmap für eine zukünftige Version.

**Comment by HendrikMennen** [comment]
Okay danke 👍
