### ISSUE TITLE
Ugly line break on order-received and view-order with germanized

### ISSUE THREAD

**Issue by jnachtigall** [vendidero/woocommerce-germanized#14]
On all other pages it looks ok but not on  `order-received` (and I think also not on `view-orders`)

This is what it correctly looks without woocommerce-germanized:
![1xcorrect](https://cloud.githubusercontent.com/assets/3307404/6543959/5f02a02a-c537-11e4-9478-f35363f1b7f6.png)

With woocommerce-germanized there is an ugly line break:
![1xincorrect](https://cloud.githubusercontent.com/assets/3307404/6543961/6411940e-c537-11e4-9833-7dc2d6933f90.png)

For the correct on the html is like:
```
<td class="product-name">
							<a href="http://XXX/">Espresso „Nightingale“</a> <strong class="product-quantity">× 1</strong><dl class="variation">
							<dt class="variation-Fllmenge">Fuellmenge:</dt>
							<dd class="variation-Fllmenge"><p>250g</p>
</dd>
						</dl>						</td>
```

whereas for the one with the ugly line break it is:

```
<td class="product-name">
							<a href="http://XXX/">Espresso „Nightingale“</a><div class="wc-gzd-item-desc item-desc"></div> <strong class="product-quantity">× 1</strong><dl class="variation">
							<dt class="variation-Fllmenge">Fuellmenge:</dt>
							<dd class="variation-Fllmenge"><p>250g</p>
</dd>
						</dl>						</td>
```
Please notice the empty `<div class="wc-gzd-item-desc item-desc"></div>` 

The solution might be simply to only print this out if it is non-empty. 
(Or have it somewhat different like on the checkout page, where the product-quantity is within its own `<td>` column and hence right aligned.)

**Comment by vendidero** [comment]
Hi,

hiding the div if no description is available won't fix the problem. Adding another td is not possible without overriding the whole oder-details template. Currently there is no other elegant way than adding a filter to the product cart name (for item desc and delivery time) which leads to that order details new line problem. You may fix that with a little CSS within your theme.. We will at least delete the empty div if no description is available.

**Comment by jnachtigall** [comment]
> We will at least delete the empty div if no description is available.

 :+1: That's actually all I'm asking for.
