### ISSUE TITLE
Markup in payment-methods.php verursacht Validationsfehler

### ISSUE THREAD

**Issue by sephentos** [vendidero/woocommerce-germanized#140]
![grafik](https://user-images.githubusercontent.com/35430448/129825450-16bf567e-f5f4-44bc-b061-88fee38b3d51.png)

siehe: 

https://github.com/vendidero/woocommerce-germanized/blob/bf79b4c8ed97f3639e133d22a18f58780843e273/templates/global/payment-methods.php#L34

Müsste die `li` nicht eher die ID haben, damit das label so in der Form funktioniert?

**Comment by vendidero** [comment]
Wir orientieren uns dabei am Original-Markup im Checkout von Woo. Grundsätzlich ist das Markup an dieser Stelle ggf. etwas unglücklich, da es sich hierbei ja nicht um Input-Felder handelt, sondern nur um eine Auflistung. Wir haben uns aber für dieses Markup entschieden um die Theme-Kompatibilität zu erhöhen, da viele Themes bzw. Gateway-Plugins für dieses Markup Styles vorsehen. Wenn dich diese Warnungen stören, kannst du das Markup natürlich per Template-Override einfach anpassen.

**Comment by sephentos** [comment]
Verstehe! Danke für die Erklärung. Habe mich im allgemeinen sowieso gefragt, wieso da for's sind, aber die Erklärung ist schlüssig.
