### ISSUE TITLE
Custom Checkbox von Versandart abhängig machen

### ISSUE THREAD

**Issue by sephentos** [vendidero/woocommerce-germanized#148]
Hallo,

möchte gerne vorschlagen, dass es möglich wäre Custom Checkboxen von Versandmethoden abhängig machen zu können, so wie es bei der Standard-Checkbox "Paketdienstleister" möglich ist ist (Bei dieser Checkbox kann man ja auswählen, für welche Versandmethoden diese angezeigt werden soll).

Durch eine solche Option könnten wir dann bspw. eine Checkbox hinzufügen, wodurch Kunden bspw. keine Nachbarschaftszustellung bei DHL-Lieferungen wünschen können.

**Comment by vendidero** [comment]
Hi,

nein, ich denke nicht, dass wir das global für alle Checkboxen anbieten werden. Du kannst das natürlich für einzelne Checkboxen ähnlich unserer Logik integrieren (lassen). Ähnlich wie hier: https://github.com/vendidero/woocommerce-germanized/blob/master/includes/class-wc-gzd-legal-checkbox-manager.php#L334

Du kannst aber auch einfach unsere DHL-Integration nutzen, dann kannst du u.a. auch den Versand an einen Nachbarn abbilden :)

Grüße
