### ISSUE TITLE
WC_Order::get_address() liefert Anrede ('title') nicht mehr zurück

### ISSUE THREAD

**Issue by megakraken** [vendidero/woocommerce-germanized#149]
Seit einem der letzten Updates liefert die [get_address()](https://woocommerce.github.io/code-reference/classes/WC-Order.html#method_get_address) Methode der [WC_Order](https://woocommerce.github.io/code-reference/classes/WC-Order.html) Klasse die Anrede nicht mehr zurück.

Zuvor war diese im zurückgelieferten Array unter dem Schlüssel 'title' hinterlegt. Nun fehlt der Schlüssel 'title' im zurückgelieferten Array.  Ist dies ein Bug oder gibt es eine andere Methode, die Anrede abzufragen?

**Comment by vendidero** [comment]
Wir implementieren den entsprechenden Filter hier: https://github.com/vendidero/woocommerce-germanized/blob/master/includes/class-wc-gzd-order-helper.php#L219 - das klappt bei meinen Tests einwandfrei.
