### ISSUE TITLE
Kasse Layout Darstellung fehlerhaft

### ISSUE THREAD

**Issue by pgirzalsky** [vendidero/woocommerce-germanized#152]
Durch das gestrige Update wurde das Layout des Checkouts (Kasse) verändert.
Hierbei kam es wohl zu einer fehlerhaften Darstellung. Die Überschrift order_review_heading sowie die Checkboxen für die rechliten Informationen etc. innerhalb des Blocks für die Auswalh der Zahlungsart ausgegeben.

![Germanized Elementor Pro Kompabilität Update](https://user-images.githubusercontent.com/48622652/151376742-11ea5d88-3bde-469d-8bcf-bfd480c8a29c.png)

Diese Checkboxen sollten vor dem "Jetzt kaufen"-Button dargestellt werden und die Überschrift vor der Artikelzusammenfasssung.
Ohne Germanized ist die Reihenfolge wieder richtig, siehe Screenshot:

![Checkout ohne Germanized](https://user-images.githubusercontent.com/48622652/151376736-582f98a1-aeb1-45b2-9575-5a09b958b3bb.png)

**Comment by vendidero** [comment]
Das ist durchaus so gewollt, da von der Button-Lösung explizit so vorgegeben. Bitte schaue hier rein: https://vendidero.de/dokument/umsetzung-der-button-loesung-im-woocommerce-checkout

Mit dem neuesten Update wird das jetzt auch korrekt für das Elementor Pro Widget umgesetzt. Wenn du das nicht möchtest, kannst du das wie in der Doku beschrieben auch deaktivieren.

**Comment by pgirzalsky** [comment]
Das ging fix! Vielen Dank für das Feedback, dann kann das Ticket geschlossen werden :)
