### ISSUE TITLE
Übersetzung wird teils nicht angezeigt 

### ISSUE THREAD

**Issue by mashuptwice** [vendidero/woocommerce-germanized#153]
Leider wird in meinem Webshop an zwei Stellen die Übersetzung nicht angezeigt, stattdessen ist der englische Originaltext zu sehen.

Es handelt sich konkret um den Kassenbereich und das Popup zum erstellen eines neuen Kundenkontos:

![woocommerce_br_account_creation](https://user-images.githubusercontent.com/54219098/151574585-9173fe79-c4a4-41b2-b67b-55e3a23c0b5f.png)
![woocommerce_br_kasse](https://user-images.githubusercontent.com/54219098/151574799-370bb9bd-0d0a-4f8a-952b-b5073f0ed4ce.png)

Laut Loco Translation existiert eine Übersetzung für diese Stellen, wird aber scheinbar nicht korrekt ersetzt:
![woocommerce_br_exists](https://user-images.githubusercontent.com/54219098/151576133-af80fff8-0aca-41bf-bca6-5ded34f1b69d.png)

**Comment by vendidero** [comment]
Hi,

die Beschriftungen der Checkboxen kannst du in den Germanized-Einstellungen unter Checkboxen unter den jeweiligen Checkboxen anpassen. Offenbar war bei der Installation von Germanized deine WP-Installation nicht auf Deutsch oder Deutsch (Sie) gestellt, sodass die Texte in Englisch (Standard) eingefügt wurden. Du kannst aber die Text-Optionen ggf. unter WooCommerce > Status > Germanized > Text-Optionen löschen neu einfügen lassen.

Grüße

**Comment by mashuptwice** [comment]
Top, das hat funktioniert. Danke für die schnelle Antwort!
