### ISSUE TITLE
Allow for Variation Form price replace

### ISSUE THREAD

**Issue by Snadex** [vendidero/woocommerce-germanized#154]
Hello,
in your latest update, you have changed how you target the price element for price update. 

In file add-to-cart-variation.js, line 36 you have
`return $wrapper.find( wc_gzd_add_to_cart_variation_params.price_selector + ':not(.price-unit):visible' ).not( '.variations_form .price' ).first();`
Here is the commit:
https://github.com/vendidero/woocommerce-germanized/commit/b50cda187954d3232c62ac3e4996acc73da45489

The problem is that in our case, and I assume other's as well, this `'.variations_form .price'` is exactly the price element we want to be updated when variation is changed. 

there is a filter
`wc_gzd_add_to_cart_variation_params.price_selector`, however since the 
`.not( '.variations_form .price' )` is after it, there is no way for us to use the filter and target the appropriate element. 

Either change the logic or introduce another filter for all of the shops that do want to change the `'.variations_form .price'` element on variation change.

The idea is very straightforward, we want to have one Price displayed on a single page. 
This price display is the `'.variations_form .price'`, it starts as a range but changes to the corresponding value once you change the variation. 

Hope it makes sense, 
Thanks,
Alex

**Comment by vendidero** [comment]
Hi there,

this commit was actually more like a feature as Germanized targets the first `.price` element on a page (which in a default Woo setup is the from-to-price added to the variable product wrapper). In case this price element is located beneath the variation form the element will not be located anymore, that's why we've changed the logic to ignore the `.variations_form` wrapper.

Will see how to overcome the issue and/or add a filter to adjust the price element. Thanks for reporting.

**Comment by vendidero** [comment]
How do you actually show that price element anyway? Germanized explicitly hides the element as soon as a new variation has been selected: https://github.com/vendidero/woocommerce-germanized/blob/master/assets/js/add-to-cart-variation.js#L160

**Comment by Snadex** [comment]
Just checked, looks like we actually load `woocommerce_template_single_price()` above the add to cart button with a filter... most probably to achieve having one price. 
Sorry, I thought it was the original variation form price which we actually hide altogether.

Well, maybe our case doesn't concern that many users but still prevents having price element inside the variations form.
If it's ok, 
maybe you can move the .not() value to the filter, maybe something like:
`return $wrapper.find( wc_gzd_add_to_cart_variation_params.price_selector + ':not(.price-unit):visible' ).not( wc_gzd_add_to_cart_variation_params.ignore_price_selector ).first();` 

This actually can be helpful if someone wants to specifically ignore whatever other price selector. 

Much appreciated for looking into this and sorry for not digging fully into it in the first place.

Thanks!

**Comment by mariusmateoc** [comment]
Hi,

I'm using a filter to move the price above the cart button and after changing variation the price is not updated anymore:

```
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_price', 10 );
add_action( 'woocommerce_after_variations_table', 'woocommerce_template_single_price', 10 );
```

I can confirm that this happens for all filters inside the `form` element from: `https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/add-to-cart/variable.php`

**Comment by vendidero** [comment]
Hi there,

could you please try it with the latest commit 208a134? We do now explicitly exclude the price within the single_variation wrap only. That should fix the issue.

Cheers

**Comment by vendidero** [comment]
@mariusmateoc @Snadex does the commit fix the issue for you?

**Comment by mariusmateoc** [comment]
@vendidero sorry for the late response, yes the commit fixes the issue.
