### ISSUE TITLE
Recalculate unit price

### ISSUE THREAD

**Issue by mariusmateoc** [vendidero/woocommerce-germanized#157]
Hi,

I use [YITH WooCommerce Dynamic Pricing and Discounts](https://yithemes.com/themes/plugins/yith-woocommerce-dynamic-pricing-and-discounts/) and try to update unit price when customers update qty on the product.

The plugin updates the price on the frontend in the following place but woocommerce-germanized hides that price:

```
<div class="single_variation_wrap">
<div class="woocommerce-variation single_variation">
    <div class="woocommerce-variation-description"></div>

    <div class="woocommerce-variation-price">
         <span class="price" style="display: none;">
              <del><span class="woocommerce-Price-amount amount">
                    <bdi>2,95&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></bdi></span>
              </del>
              <span class="woocommerce-Price-amount amount">
                    <bdi>2,31&nbsp;<span class="woocommerce-Price-currencySymbol">€</span></bdi></span>
         </span>
      </div>

    <div class="woocommerce-variation-availability"><p class="stock in-stock">2948 in stock</p>
</div>
</div>
```

There is a way to observe that price change when users change the quantity and then update the main price and recalculate the unit price?

I think this is the plugin code that updates the price:

```
public static function update_product_price() {

		check_ajax_referer( 'update-product-price', 'security' );

		$rule_id       = isset( $_REQUEST['rule_id'] ) ? sanitize_text_field( wp_unslash( $_REQUEST['rule_id'] ) ) : false;
		$product_id    = isset( $_REQUEST['product_id'] ) ? sanitize_text_field( wp_unslash( $_REQUEST['product_id'] ) ) : false;
		$qty           = isset( $_REQUEST['qty'] ) ? sanitize_text_field( wp_unslash( $_REQUEST['qty'] ) ) : false;
		$price_updated = '';

		if ( $rule_id && $product_id && $qty ) {

			$rule    = ywdpd_get_rule( $rule_id );
			$product = wc_get_product( $product_id );
			$price   = apply_filters( 'ywdpd_change_base_price', $product->get_price( 'edit' ), $product );

			if ( $rule instanceof YWDPD_Quantity_Table ) {

				$new_price     = $rule->get_discounted_price( $price, $qty, $product );
				$price_updated = YWDPD_Utils::get_product_new_price_html( $price, $new_price, $product );

			}
		}
		wp_send_json( $price_updated );

	}
```
Thanks,
Marius

**Comment by vendidero** [comment]
Hi there,

> There is a way to observe that price change when users change the quantity and then update the main price and recalculate the unit price?

Seems like the price is updated via JS. You would need to add a custom observer to see whether the variation price updates and then update the main product price too. This will trigger the unit price to be recalculated automatically as Germanized explicitly observers the main price via JS too: https://github.com/vendidero/woocommerce-germanized/blob/master/assets/js/unit-price-observer.js

Cheers
