### ISSUE TITLE
Other tax exemptions

### ISSUE THREAD

**Issue by Coernel82** [vendidero/woocommerce-germanized#167]
You have the option for small merchants to tickt "tax exemption due to small merchant" (Umsatzsteuerbefreit nach §19 UStG)
There are some other exemptions - for instance in my case Befreiung gemäß §4 Nr. 20 (a) und §4 Nr. 21 (a) (bb) UStG.

It is not important as this information is included in my invoices however if you want improve your plugin even more there is the option.

P.S.: Just rated you 5 stars.

**Comment by dennisnissle** [comment]
Hi there,

is this a product-related notice, e.g. applicable for certain products only? You might adjust the small-business text in the Germanized settings under General > Small Business
