### ISSUE TITLE
remove action from WooCommerce Product Addons compatibility

### ISSUE THREAD

**Issue by EhrhardtDa** [vendidero/woocommerce-germanized#168]
https://github.com/vendidero/woocommerce-germanized/blob/632b349e9526706832191562ee466b2ffec81ec4/includes/compatibility/class-wc-gzd-compatibility-woocommerce-product-addons.php#L23

I wan't to disable this action via my child-themes functions.php , I would be happy about some help.

Why do I need this?
Because I've moved the position of the product addons totals, so it won't be displayed within the woocommerce_product_addons_end hook.

**Comment by dennisnissle** [comment]
E.g. via:

```php
remove_action( 'woocommerce_product_addons_end', array( WC_germanized()->get_compatibility( 'woocommerce-product-addons' ), 'shopmarks' ), 11 ); 
```

Cheers
