### ISSUE TITLE
How to use the uninstall script

### ISSUE THREAD

**Issue by carokiel** [vendidero/woocommerce-germanized#171]
Hi,
we want to completely remove Germanized and Germaized Pro from our installation.
Please assist in how to use the uninstall.php

Thanks,
Caroline

**Comment by dennisnissle** [comment]
Hi there,

you won't be able to remove all data (e.g. added by Germanized Pro) as some data may be accounting-related. The uninstall script in Germanized may be activated by a custom constant defined in your wp-config.php:

`define( 'WC_GZD_REMOVE_ALL_DATA', true );`

See: https://github.com/vendidero/woocommerce-germanized/blob/master/uninstall.php#L17

If you really want to delete the accounting data, please see: https://vendidero.de/dokument/buchhaltungsdaten-zuruecksetzen

Cheers
