### ISSUE TITLE
PHP Warnung: DHL Integration + shipping_address_2 verbergen

### ISSUE THREAD

**Issue by bwp-codes** [vendidero/woocommerce-germanized#180]
Liebes Germanized-Team,

wenn in den Customizer-Einstellungen das "Adressfeld 2" verborgen wird, kann es in Kombination mit der DHL-Integration auf der Kasse-Seite zu PHP-Warnungen kommen:
`Undefined array key "label" in woocommerce-germanized/packages/woocommerce-germanized-dhl/src/ParcelLocator.php:1041`

```
$fields['shipping_address_2']['custom_attributes']['data-label-regular'] = $fields['shipping_address_2']['label'];
```

Durch das Verbergen des Feldes über den Customizer bleibt auch `$fields['shipping_address_2']['label']` leer, sodass hier eine Warnung ausgegeben wird, beim Versuch auf das Label zuzugreifen. Für z.B. `$fields['shipping_address_2']['placeholder']` in Zeile 1043 wurde bereits eine Prüfung auf das Vorhandensein des Wertes umgesetzt.

Mit dieser Anpassung würde die Zeile 1041 so aussehen und keine Warnung ausgeben, wenn kein Label definiert wurde:
```
$fields['shipping_address_2']['custom_attributes']['data-label-regular'] = isset( $fields['shipping_address_2']['label'] ) ? $fields['shipping_address_2']['label'] : '';
```
Viele Grüße!

**Comment by dennisnissle** [comment]
Hi,

danke für den Report. Fix ist hier bereits verfügbar: https://github.com/vendidero/woocommerce-germanized-dhl/commit/1567a6cfc8606fe476c9073841a087294614322a

Grüße

**Comment by bwp-codes** [comment]
Hi @dennisnissle,

danke für die schnelle Antwort - werde ich vorübergehend so übernehmen.
Gibt es schon einen Release-Datum für diesen Fix in einer kommenden Version von Germanized?

Danke und viele Grüße!

**Comment by dennisnissle** [comment]
Hi,

nein, aufgrund des geringen impacts (warnings sollten in Live-Umgebungen generell nicht ausgegeben werden) gibt es noch keinen konkreten Release-Termin. 

Grüße

**Comment by bwp-codes** [comment]
Alles klar, danke dir!
