### ISSUE TITLE
Fehlerhafte Darstellung "Keine Aktivierungs-E-Mail erhalten?"

### ISSUE THREAD

**Issue by bringticket** [vendidero/woocommerce-germanized#186]
Hallo,
Bei der Meldung "Keine Aktivierungs-E-Mail erhalten?" wird ein Punkt vor dem Text angezeigt.

![activation_email](https://user-images.githubusercontent.com/118307050/222966460-add08d54-4b86-4896-aa6f-40cc381a3885.png)

WooCommerce version:		7.4.1
WooCommerce database version:	7.4.1
Theme:				Neve
Theme Version:			3.5.3
PHP version:			8.1.2-1ubuntu2.11

**Comment by bringticket** [comment]
Hallo,
Wir haben selbst an den Übersetzungen nichts geändert und es wird auch kein Plugin dafür verwendet.
Der Text "Keine Aktivierungs-E-Mail erhalten?" kommt aus Germanized.
Um genau zu sein, aus einem der beiden Datein:

`./woocommerce-germanized/i18n/languages/woocommerce-germanized-de_DE_formal.po:"Keine Aktivierungs-E-Mail erhalten? <a href=\"%s\">Erneut zusenden</a>."
./woocommerce-germanized/i18n/languages/woocommerce-germanized-de_DE.po:"Keine Aktivierungs-E-Mail erhalten? <a href=\"%s\">Erneut zusenden</a>."
`

Um das mit den Plugin zu testen muss ich erst ein seperates Testsystem installieren, da die Website bereit Produktiv läuft.

**Comment by dennisnissle** [comment]
Hi,

wie gesagt: In der Standard-Übersetzung in der Sprachdatei von Germanized passt das alles - das kann also nach meinem aktuellen Kenntnisstand nur ein Problem mit einer anderen, installierten Erweiterung sein. Das solltet ihr in einer separaten Staging-Umgebung debuggen: https://vendidero.de/debugging-woocommerce-probleme-finden-und-beheben

Die Ausgabe erfolgt hier: https://github.com/vendidero/woocommerce-germanized/blob/master/includes/class-wc-gzd-customer-helper.php#L182

Grüße

Grüße
