### ISSUE TITLE
Double-Opt-In nicht kompatibel mit W3TC Database Caching

### ISSUE THREAD

**Issue by bringticket** [vendidero/woocommerce-germanized#187]
Hallo,
Double-Opt-In funktioniert bei aktivierten W3TC Database Caching nicht.

Bei Neuanmeldung wird der Kunde direkt ohne Aktivierungsmail bestätigt und in den Kundenbereich geleitet.
In der Benutzeransicht "DOI bestätigt" => "Ja"
_"Deaktiviere den Login und Checkout für inaktive Kunden."_ ist aktiviert.

Es wird kein Eintrag in der wp_usermeta angelegt.
`SELECT * FROM wp_usermeta WHERE meta_key = '_woocommerce_activation';`

Wird W3TC Database Caching deaktiviert, funktioniert so weit wir testen konnten Double-Opt-In wie erwartet.

WooCommerce version:		7.4.1
WooCommerce database version:	7.4.1
Theme:				Neve
Theme Version:			3.5.3
PHP version:			8.1.2-1ubuntu2.11
W3TC Version: 2.3.0
Getestet mit APCu Cache

**Comment by dennisnissle** [comment]
Hi,

ich kann euch da leider nur bedingt weiterhelfen. DB Caching ist eine komplexe Sache, die wirklich sehr gut konfiguriert werden muss, damit das reibungslos funktionieren kann. Germanized verwendet den Hook `woocommerce_created_customer_notification` um beim Versenden der Registrierungsbestätigung durch Woo einzugreifen. Dort werden die Meta-Daten des Users eingefügt. S.a.: https://github.com/vendidero/woocommerce-germanized/blob/master/includes/class-wc-gzd-customer-helper.php#L799

Das müsstet ihr also im Zweifel genauer debuggen lassen, warum dieser Hook nicht ausgeführt wird oder warum das fehlschlägt.

Grüße
