### ISSUE TITLE
Germanized ändert den Betrag des Wertgutscheins nach Statuswechsel

### ISSUE THREAD

**Issue by viktormiller** [vendidero/woocommerce-germanized#188]
Hallo zusammen,

wir beobachten ein Problem mit Wertgutscheinen, wenn Product Bundles verwendet werden und über Vorkasse bezahlt wird. 
In dieser Konstellation wird nach einem Statuswechsel von `In Wartestellung` auf `In Bearbeitung` der Betrag des Wertgutscheins und der Bestellsumme geändert und bei einem erneuten Statuswechsel auf `Abgeschlossen` eine fehlerhafte Versandbestätigung per E-Mail verschickt.

Wir konnten den Fehler auf einer frischen Wordpress-Installation nachstellen, indem wir neben "WooCommerce" und "Germanized" noch das Plugin "WooCommerce Product Bundles" installieren. 
Der Fehler tritt auf, wenn eine Bestellung eines Product Bundles mit einem Wertgutschein erstellt wird und die Bezahlmethode Vorkasse ausgewählt wird. Führt man anschließend einen Statuswechsel von `In Wartestellung` auf `In Bearbeitung` aus, werden der Wertgutschein und die Bestellsumme verändert.

Anbei zwei Screenshots von vor und nach dem Statuswechsel:

In Wartestellung (Wertgutschein und Bestellsumme noch korrekt)
<img width="852" alt="Bestellung in Wartestellung" src="https://user-images.githubusercontent.com/6901369/236491347-af4681df-a9e6-42d9-b555-1e00cd974328.png">

In Bearbeitung (Wertgutschein und Bestellsumme falsch)
<img width="851" alt="Screenshot 2023-05-05 at 23 32 50" src="https://user-images.githubusercontent.com/6901369/236491486-14d3097f-eaca-4423-b446-e7bbf6bb7567.png">

Der Fehler tritt nicht auf, wenn die Option "Wertgutschein" im Gutschein abgewählt wird.

**Comment by dennisnissle** [comment]
Hi,

kannst du mir Zugriff auf die Staging-Umgebung ermöglichen, damit ich mir das dort genauer ansehen kann? Gut wäre auch eine kurze Schritt-für-Schritt Anleitung, wie ich das dort konkret reproduzieren kann. Alles weitere gern per Mail an help@vendidero.de

Grüße

**Comment by viktormiller** [comment]
Alles klar, den Zugang zur Stage schicke ich euch per Mail, sowie die Schritt-für-Schritt Anleitung.

**Comment by viktormiller** [comment]
Kurzes Update. 

Der Fehler tritt auch ohne ein Bundle auf, die Schritte sind aber immer noch die gleichen. Gemischter Warenkorb mit Produkten, von denen eines/mehrere durch einen Warengutschein reduziert sind und andere nicht. Zahlungsmethode Vorkasse (Direct bank transfer) mit Statuswechsel von In Wartestellung (On hold) auf In Bearbeitung (Processing).

Anbei zwei Screenshots.

Status On Hold
<img width="853" alt="Voucher in Status On Hold" src="https://user-images.githubusercontent.com/6901369/237009070-dea53939-2295-4104-80a4-933f00fdcc0d.png">

Status Processing
<img width="816" alt="Voucher in Status Processing" src="https://user-images.githubusercontent.com/6901369/237009094-1e500629-8beb-473a-828a-bfb60555296c.png">

In diesem Beispiel sind zwei Produkte im Warenkorb, von denen eigentlich nur eines reduziert sein sollte. Beim Statuswechsel beträgt die Gesamtsumme des Vouchers die Gesamtsumme des Warenkorbs ohne die Versandkosten, was falsch ist.

Der Voucher übernimmt also beim Statuswechsel die gesamten Kosten des Warenkorbs ohne die Versandkosten.

**Comment by dennisnissle** [comment]
Ok, verstehe. Also tritt das Problem nur dann auf, wenn der Wertgutschein auf bestimmte Produkte limitiert ist? 

Ich denke nicht, dass es sich in diesem Fall dann (steuer-)rechtlich um einen Wertgutschein handelt. Der Wertgutschein ist mit einem Zahlungsmittel gleichzusetzen. Diese Definition beißt sich m.M.n. mit einer solchen Beschränkung. Ich werde mir das Thema aber dennoch genauer ansehen.

Grüße

**Comment by dennisnissle** [comment]
@viktormiller 

Ich denke das Problem konnte ich mit dem letzten commit beheben. Du kannst das gern testen. Generell ist es aber ziemlich ungewöhnlich a) einen prozentualen und b) einen auf spezifische Produkte limitierten Wertgutschein zu nutzen. Danke dennoch für den Report!

Grüße

**Comment by viktormiller** [comment]
Hi Dennis,

sieht sehr gut aus! Ich habe es auf unserer Stage erfolgreich getestet. 

Könnt ihr schon abschätzen, wann die Änderung released wird?

**Comment by dennisnissle** [comment]
Hi @viktormiller,

das kommt automatisch in das nächste Update. Ich denke spätestens in 2 Wochen.

Grüße
