### ISSUE TITLE
Ausgabe der Warenkorb-Kurzbeschreibung im Product Listing

### ISSUE THREAD

**Issue by bennimedia** [vendidero/woocommerce-germanized#189]
Hallo,
aktuell wird bei mir im Listing die Produkt Kurzbeschreibung ausgegeben. 
Ich möchte jetzt gerne die Warenkorb-Kurzbeschreibung dafür ausgeben lassen.

Folgendes Code habe ich aktuell für die Produkt-Kurzbeschreibung verwendet:
```
` add_action( 'woocommerce_after_shop_loop_item_title', 'woo_show_excerpt_shop_page', 5 );
  function woo_show_excerpt_shop_page() {
   global $product;
 
   echo '<div class="listing-desc">'.substr ($product->post->post_excerpt, 0, 108 )."...</div>";
 }
```

Was muss ich ändern, damit die die **Warenkorb Kurzbeschreibung** angezeigt wird?

**Comment by dennisnissle** [comment]
Hi,

schau dir gern mal unsere [Methode](https://github.com/vendidero/woocommerce-germanized/blob/master/includes/abstracts/abstract-wc-gzd-product.php#L572) dafür an. Beispielhaft ist das auch [hier](https://github.com/vendidero/woocommerce-germanized/blob/master/includes/wc-gzd-cart-functions.php#L140) zu sehen. 

PS: Bitte wende dich in Sachen Support entweder an unser [Help Desk](https://vendidero.de/dashboard/help-desk) oder an unser Forum auf [wp.org](https://wordpress.org/support/plugin/woocommerce-germanized/). Bitte beachte auch, dass individueller Code-Support nicht Teil unseres Supports ist. 

Grüße
