### ISSUE TITLE
Installed Master: items can't be added to cart

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [vendidero/woocommerce-germanized#19]
I checked out the latest version of the plugin (forked it) but after uploading the files and replacing the release version, items can no longer be added to the cart.

The confirmation message (successfully added to cart) is shown, however the item instantly vanishes without any messages from the cart. When entering cart page is says: your cart is empty.
Is there a bug in the github master version?

I reuploaded the latest release version and add-to-cart-functionality is back.

just wanted to let you know

**Comment by vendidero** [comment]
Cannot reproduce that problem.. Did you delete the old version entirely?

**Comment by s-a-s-k-i-a** [comment]
yes, I deleted it entirely. Also any templates I had duplicated in my theme folder.
Weird thing.

As I said, after re-uploading and replacing the master github version with the official release, the addtocart-process worked flawlessly again, so there must be something about it…

**Comment by vendidero** [comment]
do you have WP_DEBUG activated? Do you get any error or warning?
We actually didn't change anything in regard to the add-to-cart-process.

**Comment by s-a-s-k-i-a** [comment]
Hey again!
I made a screencast to show you.
https://www.youtube.com/watch?v=mJ_WB19FDis (720p verfügbar)

WP-Debug sagt mir nichts ausser:
Notice: wp_enqueue_script wurde fehlerhaft aufgerufen. Skripte und Styles sollten nicht vor den Hooks wp_enqueue_scripts, admin_enqueue_scripts oder login_enqueue_scripts registriert oder eingebunden werden. Schau Dir Debugging in WordPress an, um mehr darüber zu erfahren. (Diese Meldung wurde in Version 3.3 hinzugefügt.) in /wp-includes/functions.php on line 3560

Notice: wp_script_is wurde fehlerhaft aufgerufen. Skripte und Styles sollten nicht vor den Hooks wp_enqueue_scripts, admin_enqueue_scripts oder login_enqueue_scripts registriert oder eingebunden werden. Schau Dir Debugging in WordPress an, um mehr darüber zu erfahren. (Diese Meldung wurde in Version 3.3 hinzugefügt.) in /wp-includes/functions.php on line 3560

**Comment by vendidero** [comment]
Hi,

Did you try the commit I mentioned in the previous post? Just want to make sure that the problem lies within the latest commit..

**Comment by s-a-s-k-i-a** [comment]
see my previous post.

**Comment by s-a-s-k-i-a** [comment]
so yes, confired : problem lies within latest commit

**Comment by vendidero** [comment]
Hi,

we changed the hook which adds the Germanized hooks to woocommerce_loaded to allow themes to remove them afterwards.. Did you try to use a default theme? Still facing those problems?

**Comment by s-a-s-k-i-a** [comment]
I didn't try a default theme.. very sorry but changing the theme means big hassle afterwards to set up everything again.. because it is a production site :)

What can I do to make my theme fit with that hook-change?

The problem exists only when using the latest version; before that the plugin worked perfectly fine with my theme... it is called Sistina (by Yithemes)

why did you have to change that hook, oh why? ( ;) ) 

thanks in advance

**Comment by alx0815** [comment]
Same here. After the Update with the WP Updater the "Grundpreis" for the product variations was shown as "undefined". I mailed with Ben von Kadence Themes and after all i used the version of GidHub (2 hours ago).

Now a woocommerce customer is able to put a product in the Basket and it will be there for 2 seconds.... than it is empty. 

Bevor these Updates everything was fine and works perfect with my theme from Kadence called "virtue". Any ideas? 

Link: www.indie-roasters.de/shop

Would be nice to use this plugin .)

Cheers

Alx

**Comment by vendidero** [comment]
Hi there,

just added a new commit. I've installed virtue and was facing the same problem so I was able to do some further researching and made some fixes. It works fine for me now. Please give me some feedback whether this fix does work for you too..
And let me give you an advice: Don't use the latest commits for production purposes :)

Cheers

**Comment by alx0815** [comment]
perfect! Thank you very much for your Time and this working solution! Here it works also fine.
I know that handling with Beta Stuff is difficult and risky.... time is a bandit and i did an Update to quickly.
When will this Changes arrive in an stable Version?

Thanx

Alx

**Comment by s-a-s-k-i-a** [comment]
Confirmed!
Perfectly working now. No more cart-vanish-bug

Thanks!

**Comment by gerdneuman** [comment]
Hi @vendidero When will this bug fix be released? We are also using virtue. I would like to express the wish for faster bug fix releases (http://de.wikipedia.org/wiki/Release_early,_release_often). Maybe have a feature branch (upcoming 1.4) and also a branch for bug fixes only (1.3.x).

To us this would be important because due to the XSS fix in WooCommerce we want to upgrade to WooCommerce 2.3.9 but on the other hand I know that we will probably run into problems due to this bug which is only fixed on github master (which probably includes some other commits)

So a 1.3.2 release would be highly appreciated.

**Comment by s-a-s-k-i-a** [comment]
Hi Gerd Neumann,

I downloaded the latest Master version from Github. Please use this link to download the zip-file:
https://github.com/vendidero/woocommerce-germanized/archive/master.zip

Unzip it and place the files located in the unzipped folder (woocommerce-germanized-master) in your woocommerce germanized folder located here on your FTP:
/wp-content/plugins/woocommerce-germanized/

If needed (your FTP client asks you), replace files.
Please backup your current woocommerce-germanized folder contents beforehand, in case you customized any files.

As I said, I am using the current Master and it works just fine. Could not find any more bugs since this issue. 

Best regards
Saskia

**Comment by gerdneuman** [comment]
@s-a-s-k-i-a Are you using the current master as of *now* or as of *9 days ago*? Just asking...

**Comment by s-a-s-k-i-a** [comment]
I am using the current Master. including commit of May 13

**Comment by gerdneuman** [comment]
@s-a-s-k-i-a thanks for the info, I really appreciate this.

@vendidero In general, still I do not like the idea of having to use git master, hope you might consider switching to a more "release early, release often" policy. I already noticed this earlier (when 1.2.3 was the stable version), that bug fixes take a relatively long time until they reach the users because bugs get fixed on master but no proper release is done.

Generally I am not a big fan of fiddling around with ftp and manually pasting files, it's just too error prone. I still very much prefer the default wp updater way of doing it.

**Comment by s-a-s-k-i-a** [comment]
WP repository has been updated to Germanized 1.3.2
So now you can update via WP Backend

**Comment by gerdneuman** [comment]
@s-a-s-k-i-a Great stuff, thanks!   :+1:
