### ISSUE TITLE
Action hook when order is paid

### ISSUE THREAD

**Issue by strarsis** [vendidero/woocommerce-germanized#193]
WooCommerce Germanized adds a confirmation email for when the order is paid.
Is there an action hook that can be used for the event when orders are paid?

The [`woocommerce_order_action_paid_for_order_notification`](https://github.com/vendidero/woocommerce-germanized/blob/v3.13.5/includes/admin/class-wc-gzd-admin.php#L75) action hook appears to be a fitting candidate, however, it does not seem to be fired when the order is paid.

```php
add_action(
    'woocommerce_order_action_paid_for_order_notification',
    'orderwaspaidfn',
    10,
    1
);
````

**Comment by strarsis** [comment]
Thanks for clearing this up. It really looked to me as if that action hook (`woocommerce_order_action_paid_for_order_notification`) can be used. But `woocommerce_payment_complete` is so much better.

**Comment by strarsis** [comment]
@dennisnissle: Let's say an order is to be paid via direct bank transfer (async. payment).
When the bank transfer was successful, the shop manager has to mark the order as paid - where can this be done in WooCommerce? Changing the order status from "Pending payment" to "Processing" does not appear to trigger the hook

**Comment by dennisnissle** [comment]
@strarsis - in this case you may only rely on status change events.
