### ISSUE TITLE
Delivery time displayed twice in My account > View order  // Missing in Cart

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [vendidero/woocommerce-germanized#20]
Hi again :)

Something else I noticed:
The delivery time is displayed twice in the View Order page under My account.
![doppeltelieferzeiten-in-meinkonto-vieworder](https://cloud.githubusercontent.com/assets/3524165/7564891/65cb75da-f7eb-11e4-82a4-4c3ff20a5bae.png)

And missing from the cart order list completely:

![warenkorb-keinelieferzeit](https://cloud.githubusercontent.com/assets/3524165/7564902/7e79d324-f7eb-11e4-9623-0f55ec8877b7.png)

I just noticed it - and it is like this in the stable release as well as in the github master.

Is that my theme again? The Cart content display code is 1:1 woocommerce code...hm

Thanks for your help again!

**Comment by panploenes** [comment]
Hey just checked this and can confirm that the delivery time is displayed twice on the View Order page under My account. But on the cart page i have everything how it should be.

**Comment by vendidero** [comment]
Fixed within the latest commit..

**Comment by vendidero** [comment]
Just checked the problem regarding delivery time within cart with your child theme - displays perfectly :)
Maybe there is some plugin interfering?

**Comment by panploenes** [comment]
You guys are amazingly fast!!! Really appreciate your dedication to this.

**Comment by s-a-s-k-i-a** [comment]
Thanks for the quick fix!

Did you check the delivery time display in the cart with a single product or with a variant?

**Comment by vendidero** [comment]
Hi,

well then this has to be a plugin problem. You may deactivate one plugin after another and check again..
(start with the WooCommerce Plugins first..)

**Comment by s-a-s-k-i-a** [comment]
Found it!

When deactivating:
WPML Multilingual CMS
WPML Media
WPML Sticky Links
WPML String Translation
WPML Translation Management

The deliveryinfo and mini description was displayed correctly. Note: I left WooCommerce Multilingual activated.

Conclusion:
imcompatibility with WPML :(

**Comment by s-a-s-k-i-a** [comment]
Ok.. I reactivated WPML Main Plugin at its dependencies. 
Deactivated WooCommerce Multilingual, which ativates WPML for WooCommerce.

Now, everything is displayed in the cart page, however this is not an option, if you want to use WPML with WooCommerce XD

**Comment by vendidero** [comment]
Allright.. Good to know. I will have some further investigation :)

**Comment by vendidero** [comment]
Could you give it a try with the newest commit?

**Comment by s-a-s-k-i-a** [comment]
Thank for the fix ;)

P.S.: Are you married?

**Comment by vendidero** [comment]
not yet :)
