### ISSUE TITLE
Different result when using `has_term()` on `$product` and `$gzd_product`.

### ISSUE THREAD

**Issue by mariusmateoc** [vendidero/woocommerce-germanized#200]
I'm using the following filter and getting different results when I use `has_term()` using `$product` than when I use it with `$gzd_product`. 

Don't know if this is what should happen or is a bug.

```php
// Dynamically recalculate unit prices before retrieving them
add_filter( 'woocommerce_gzd_before_get_unit_price_html', function( $gzd_product ) {
    global $product;
    
    // when using $product this return true
    if ( has_term( 'leuchten', 'product_cat', $product->get_id() ) ) {
        return;
    }

    // when using $gzd_product this return false
    if ( has_term( 'leuchten', 'product_cat', $gzd_product->get_id() ) ) {
        return;
    }

    $gzd_product->recalculate_unit_price();
}, 10 );
```

**Comment by dennisnissle** [comment]
Well, obviously the global $product you are referring to does not match the actual product instance injected into the filter. If you wanted to get the original $product from the $gzd_product you could use:

`$wc_product = $gzd_product->get_wc_product();`

Using the global $product doesn't make sense within the filter.

Best,
Dennis
