### ISSUE TITLE
Question about the onboarding wizard

### ISSUE THREAD

**Issue by zaherg** [vendidero/woocommerce-germanized#206]
Hey there,

I noticed that I am not always redirected to the wizard once I installed the plugin.

So, is the wizard important or the plugin can function perfectly without running it?

**Comment by dennisnissle** [comment]
The plugin works just fine without it - it is just a "helper" to adjust the initial (default) settings. Whether you are redirected (after an update) to the onboarding wizard depends on whether you've set a revocation page within your general settings under Germanized > General. See: https://github.com/vendidero/woocommerce-germanized/blob/master/includes/class-wc-gzd-install.php#L299

Best,
Dennis

**Comment by zaherg** [comment]
Amazing, thank you so much Dennis
