### ISSUE TITLE
Onboarding Screen hängt

### ISSUE THREAD

**Issue by bratkartoffel** [vendidero/woocommerce-germanized#208]
Hallo,

seit dem neuesten Update (3.17) komme ich nicht mehr über den Onboarding Screen hinaus. Egal welchen Menüpunkt ich im Admin-Backend auswähle, er wirft mich immer wieder auf den Screen.
Wenn ich das Plugin im `wp-content/plugins` umbenenne oder entferne, dann geht das Backend wieder normal.

// Edit: Nach dem Downgrade auf 3.16.9 funkioniert alles wieder normal.

Grüsse,
BK

**Comment by dennisnissle** [comment]
Hi,

kann es sein, dass du Probleme mit dem Caching hast? Für den redirect wird eine temporäre Option erstellt, die auf Existenz geprüft wird. Vor dem redirect wird die Option gelöscht und dürfte damit in der DB nicht mehr vorliegen. Möglicherweise tut sie das bei dir aber weiterhin?

https://github.com/vendidero/woocommerce-germanized/blob/master/includes/class-wc-gzd-install.php#L114

Grüße

**Comment by bratkartoffel** [comment]
Hallo,

danke, ich schau mal was ich dazu bei den aktiven Plugins finde. Frage mich aber, wie ich den Cache leeren / resetten soll, wenn ich nicht auf die entsprechenden Seiten komme.

Grüsse und Danke,
BK

**Comment by dennisnissle** [comment]
Je nach Plugin geht das über die Admin Toolbar (auf jeder Admin-Seite)..

**Comment by bratkartoffel** [comment]
Ja, das hat leider nicht geklappt. Habe nun das Caching-Plugin abgeschaltet (APCu Manager), jetzt läuft wieder alles.
Bei Gelegenheit muss ich mir das mal genauer anschauen, aber nach einer kurzen Recherche passiert das bei dem Cache anscheinend des öfteren.
Danke!
