### ISSUE TITLE
_mini-desc (Short description) can't be saved correctly in WC products backend

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [vendidero/woocommerce-germanized#21]
Uhm.. hi!

there seems to be a bug when trying to add a mini description to variants.

I add a text to the mini desc-box, hit update. Then it is displayed in frontend.
However when I re-enter the product in WC backend the mini-desc is visibly gone. When I change any value and hit update again, the mini-desc is also gone from frontend.

**Comment by vendidero** [comment]
Fixed :)
