### ISSUE TITLE
Upgrade min PHP Version

### ISSUE THREAD

**Issue by kurzi2704** [vendidero/woocommerce-germanized#210]
As you are using typed properties in /woocommerce-germanized/vendor/dvdoug/boxpacker/src/ItemList.php you should remove the types here or upgrade the min required PHP version to at lest 7.4 below that PHP Version it would cause a fatal error. 
![2024-10-16_08-54-20](https://github.com/user-attachments/assets/34d4078f-c9f7-496d-8199-51656cf72bac)

**Comment by dennisnissle** [comment]
Hi there,

the whole boxpacking logic will only be loaded for > 7.1. See:
https://github.com/vendidero/woocommerce-germanized-shipments/blob/master/src/Package.php#L196

Best,
Dennis

**Comment by dennisnissle** [comment]
I'll fix that, thanks for reporting!
