### ISSUE TITLE
WooCommerce =>9.4.0: The "banner" layout is deprecated. Please use "thumbnail" instead to display a image

### ISSUE THREAD

**Issue by sephentos** [vendidero/woocommerce-germanized#213]
Moin,

die Datei

`includes/admin/notes/class-wc-gzd-admin-note.php`

enthält diese Zeile:

```
				$note->set_layout( 'banner' );
```

Dies verursacht ab WooCommerce 9.4.0 folgende Deprecation Meldung:

```
	public function set_layout( $layout ) {
...
		if ( 'banner' === $layout ) {
			wc_deprecated_argument( 'Note::set_layout', '9.4.0', 'The "banner" layout is deprecated. Please use "thumbnail" instead to display a image.' );
		}
...
```

**Comment by dennisnissle** [comment]
Hi,

schau mal [hier](https://github.com/vendidero/woocommerce-germanized/commit/2ea4a5e06c4ea5115755ab7da72c8fed9bc16bae), das wurde bereits gepatched und kommt in das nächste Update.

Grüße
