### ISSUE TITLE
Rabatte greifen nicht wenn Limits gesetzt sind

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [vendidero/woocommerce-germanized#23]
Hallo Dennis,

irgendetwas ist mit den Rabatten nicht in Ordnung. Reguläre Rabatte greifen aber sobal Warenkorblimits gesetzt sind, meckert er:
![201505142_1505-screenshot](https://cloud.githubusercontent.com/assets/3524165/7771802/55dc99ee-009a-11e5-88d6-0583772c6a16.png)
![201505142_1505-screenshot_1](https://cloud.githubusercontent.com/assets/3524165/7771804/581fdf5e-009a-11e5-9438-5652330a30f7.png)
![201505142_1505-screenshot_2](https://cloud.githubusercontent.com/assets/3524165/7771808/5c72ca12-009a-11e5-85a5-63845c66ec4b.png)

WP org Support-Thread: https://wordpress.org/support/topic/rabatt-wird-vom-nettowarenwert-angezeigt-und-so-exportiert?replies=6#post-6982435

**Comment by s-a-s-k-i-a** [comment]
Problem scheint nur aufzutreten, wenn ein Maximallimit angegeben wird. Wenn lediglich ein Mindestbestellwert festgelegt wird, greift der Gutschein so wie er soll.

**Comment by vendidero** [comment]
Hi Saskia,

hast du WooCommerce Germanized mal deaktiviert? Denke das liegt eher im Allgemeinen an WooCommerce. Verstehe aber noch nicht genau was daran falsch ist - der Maximalbetrag beträgt 29,99 - der Bestellbetrag in deinem Beispiel beträgt insgesamt 30,48 - da sollte der Gutschein doch nicht anwendbar sein?

**Comment by s-a-s-k-i-a** [comment]
Warenkorbrabatt bezieht sich auf den Warenkorb und nicht auf Warenkorb + Versand ;)

Moment ich teste mal mit  ohne Germanized

**Comment by s-a-s-k-i-a** [comment]
Hast Recht ist ein WooCommerce Problem.

Ich hab Germanized deaktiviert udn nochmal probiert. Selbes Ergebnis.
Dann den Versand kostenlos eingestellt. So dass der Gesamtbetrag 25,98 ist. also unter 29,99:
Selbes Ergebnis. Gutschein greift nicht.
Ergo: WooCommerce Issue

**Comment by s-a-s-k-i-a** [comment]
Issue fixed in WooCommerce https://github.com/woothemes/woocommerce/commit/f1af777368335ed5ad89351538e000762bb3674c
