### ISSUE TITLE
i18n: Angebots-Einheitspreis not Aktions-Einheitspreis

### ISSUE THREAD

**Issue by gerdneuman** [vendidero/woocommerce-germanized#24]
In your [translation](https://github.com/vendidero/woocommerce-germanized/blob/89a45f9b6be79ca5dbe95503a137eda1aea7862e/i18n/languages/woocommerce-germanized-de_DE.po#L166) it should be Angebots-Einheitspreis (not "Aktions")

This way it is in synced with [WooCommerce translations](https://www.transifex.com/projects/p/woocommerce/viewstrings/#de_DE/woocommerce-pot/19010938?q=sale) where "(on) sale" is "Angebot" and not "Aktion".

**Comment by vendidero** [comment]
Thanks.. Fixed!
