### ISSUE TITLE
<span class="tax small tax-label"></span> in order overview / Woo Subscriptions 2.0

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [vendidero/woocommerce-germanized#25]
I am testing Woothemes Subscription plugin with Germanized atm, and found that line 944 in https://github.com/vendidero/woocommerce-germanized/blob/master/woocommerce-germanized.php is causing the following display issue in my account > order single overview:

![201510293_0310-screenshot](https://cloud.githubusercontent.com/assets/3524165/10595524/9482e5da-76d9-11e5-9a07-a47293272d15.png)

When I remove the span that surrounds tax info, I solve this. But I guess that's not how it should be. 
Incompatibility with Woothemes Subscriptions plugin or does this also happen with regular product orders?

**Comment by vendidero** [comment]
Hi there,

Woo Subscriptions seems to escape the HTML used within order_totals. The HTML is not really necessary (just for some better Layout adaptions). I'll remove the HTML within the next commit..

Cheers
