### ISSUE TITLE
Checkout - Wrong html order

### ISSUE THREAD

**Issue by grosssmutttr** [vendidero/woocommerce-germanized#29]
Hi there,

this is a small design issue.
When you are on the checkout page and it displays the terms with a checkbox the checkbox shouldn't be in the <label> tag.

<code>-label class="checkbox" for="legal"--input type="checkbox" class="input-checkbox" name="legal" id="legal"- Mit Ihrer Bestellung erklären Sie sich mit unseren -a href="http://url.de/agb/" target="_blank"-Allgemeinen Geschäftsbedingungen-/a- und -a href="http://url.de/widerrufsbelehrung/" target="_blank"-Widerrufsbestimmungen-/a- einverstanden.-/label</code>

This causes the elements to overlap.

**Comment by grosssmutttr** [comment]
Fixed it by adding this to the functions.php:
<code>remove_action( 'woocommerce_review_order_before_submit', 'woocommerce_gzd_template_checkout_legal', wc_gzd_get_hook_priority( 'checkout_legal' ) );

	function woocommerce_gzd_template_checkout_legal() {
		echo '<p class="form-row legal terms">' . ( get_option( 'woocommerce_gzd_display_checkout_legal_no_checkbox' ) == 'no' ? '<input type="checkbox" class="input-checkbox" name="legal" id="legal" />' : '' ) . ' ' .'<label class="checkbox" for="legal">'. wc_gzd_get_legal_text() . '</label></p>';
	}
        
add_action( 'woocommerce_review_order_after_shop_table', 'woocommerce_gzd_template_checkout_legal', wc_gzd_get_hook_priority( 'checkout_legal' ) );</code>

**Comment by vendidero** [comment]
Fixed within one of our last commits..

**Comment by grosssmutttr** [comment]
The text still overlaps the checkbox and I'm using the latest version...

**Comment by vendidero** [comment]
Well we use the same HTML order/formatting as WooCommerce does. Maybe you should try a default theme or fix that issue via CSS. See the HTML order here (maybe you are using a release and not the latest branch):
https://github.com/vendidero/woocommerce-germanized/blob/master/templates/checkout/terms.php

cheers
