### ISSUE TITLE
after Woocoomerce 2.5.2 update php error: Class 'WC_GZD_Admin' not found 

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [vendidero/woocommerce-germanized#31]
Gerade auf WooCommerce 2.5.2 aktualisiert und bekomme jetzt folgenden php error:
"PHP message: PHP Fatal error:  Class 'WC_GZD_Admin' not found in /var/www/mydomain.de/htdocs/wp-content/plugins/woocommerce-germanized/includes/admin/settings/class-wc-gzd-settings-germanized.php on line 130" while reading response header from upstream, client: xx.xxx.xxx.xx, server: mydomain.de, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "www.mydomain.de"

Irgendne Idee?

**Comment by vendidero** [comment]
Hi,

stimmt, das ist mir auch bereits einmal untergekommen. Kann eigentlich nur passieren, wenn zufällig GZD_Admin noch nicht included wurde (das passiert nur einmal beim Update) und man sich zu diesem Zeitpunkt im Frontend befindet. Im neuesten Commit ist das bereits behoben.. Werde dazu wahrscheinlich in Kürze einen Fix als Version veröffentlichen.

Grüße

**Comment by s-a-s-k-i-a** [comment]
Hab rerolled auf wc 2.5.1 da der fehler meine Seite unerreichbar machte.. auch nach vps Neustart und nachdem ich den WC ordner testweise mal komplett aus dem plugin Verzeichnis gelöscht hatte... hat sich komplett festgefahren.
NAch rerol auf 2.5.1 Seite wieder problemlos erreichbar in kombi mit GZD.

**Comment by vendidero** [comment]
Wenn dann, solltest du evtl. den germanized Ordner löschen/umbenennen. Am besten mal den neuesten Commit von Germanized einspielen (oder auf das Release in Kürze warten) und dann dürfte es da keine Probleme mehr geben.
