### ISSUE TITLE
Erroreous JavaScript code

### ISSUE THREAD

**Issue by jnachtigall** [vendidero/woocommerce-germanized#33]
Hi,

I just had a quick look at the JS (while searching for how to do something). I stumpled upon this, just thought to let you know:

1. Missing semicolon in https://github.com/vendidero/woocommerce-germanized/blob/13ce312fd724718e7ce8f4e987870469e739cd09/assets/js/add-to-cart-variation.js#L29
2. Also $form without `var` defines a global variable which can have all kinds of side effects

Wouldn't the use of jshint or eslint be an option? It's easy to make mistakes in js, hence most other projects I know use either of these. These are just errors I caught by eys accidentically, there are probably some more unstable stuff in there.

Unfortunately, JS tolerates 99% of not-so-optimal code. If you ever hit the 1% (another plugin having `$form` then this can be really extremely hard to debug, same for `$wrapper`)

**Comment by vendidero** [comment]
Hi,

fixed that within latest commit. Will definitely be an option for the future to include jshint.

Cheers
