### ISSUE TITLE
2 failures on checkout success page

### ISSUE THREAD

**Issue by hub2000** [vendidero/woocommerce-germanized#35]
Hello,
there are two errors:
`Warning: Attempt to assign property of non-object in /home/wallartprofis/public_html/wp-content/plugins/woocommerce-germanized/includes/wc-gzd-product-functions.php on line 24`

`Fatal error: Call to a member function has_product_units() on a non-object in /home/wallartprofis/public_html/wp-content/plugins/woocommerce-germanized/includes/wc-gzd-cart-functions.php on line 92`

When i deactivate the "Bestellbestätigungs-Daten" the failure is not visible, but where could be the problem?

brg
hub2000

**Comment by vendidero** [comment]
Hi,
seems to me like there is a problem while creating the product object. Did you customize the success page? Please try to deactivate third party WooCommerce Plugin and/or your theme to start checking where the error might be hiding..

cheers
