### ISSUE TITLE
Amazon Payments Advanced & Mehrstufige Kasse

### ISSUE THREAD

**Issue by ForCase** [vendidero/woocommerce-germanized#36]
In der Kombination der mehrstufigen Kasse mit dem payment Prozessor "amazon payments advanced" funktioniert der checkout-Prozess nicht. Nach der Anmeldung bei amazon wird der amazon-frame auf der ersten Stufe korrekt angezeigt. Bei klick auf weiter (zur Stufe 2) hängt der Prozess und kehrt sofort zur ersten Stufe zurück.
Das PlugIn (https://www.woothemes.com/products/pay-with-amazon/) funktioniert einwandfrei, wenn der mehrstufige Checkout-Prozess deaktiviert ist.

Bitte um Feedback bzw. einen Workaround. Vielen Dank und beste Grüße
Moritz

**Comment by vendidero** [comment]
Hi,

am besten du sendest mir mal eine Kopie der neuesten Version des entsprechenden Plugins an meine Email-Adresse info@vendidero.de - dann schaue ich mir das mal etwas genauer an und gucke, ob wir da  eine Kompatibilität herstellen können.

Grüße

**Comment by vendidero** [comment]
Hi,

das Problem werden wir im nächsten Update der Pro-Version beheben. Danke für die Mithilfe!

Grüße

**Comment by dfarin** [comment]
Kann es sein das es hier immer noch Probleme gibt?
Ich habe das gerade mit der Version 1.5.7 und dem gleichen Plugin versucht, der Checkout Prozess bricht immer noch ab wenn Amazon als Zahungsvariante genutzt wird.
