### ISSUE TITLE
Lieferzeit // delivery time

### ISSUE THREAD

**Issue by smatplacid** [vendidero/woocommerce-germanized#4]
[english issue below]

Hallo,

seit Germanized installiert ist, kann man in der Post-Box im Backend nicht mehr die vordefinierten Lieferzeiten auswählen. Stattdessen hat man eine neue Box, welche ähnlich wie Tags funktioniert und ich kann nur eine häufig genutzte Lieferzeit auswählen.
Für den Kunden ziemlich umständlich.
Kann das im kommenden Update berücksichtigt werden?

Vielen Dank.

----

Hello, 

since Germanized is installed, I have no chance to use the predefined delivery times. Instead I have a tag-like box, where I can choose from most used delivery times.
It's a mess for the client.
Can you make it as before in the next update?

Thanks a lot.

![bef_aft](https://cloud.githubusercontent.com/assets/10724596/5918372/38f2223a-a628-11e4-8c82-6f9bccad4466.jpg)

**Comment by heynad** [comment]
One also has to enter at least 2 characters (which must be right!) into the tag-like search input box to get results. Just a simple dropdown would be sufficient or a select2 box as the rest of WooCommerce and Wordpress uses these days.

**Comment by vendidero** [comment]
Hi,

added that feature in latest commit..
