### ISSUE TITLE
language override folder

### ISSUE THREAD

**Issue by Tobias-Conrad** [vendidero/woocommerce-germanized#40]
Übersetzung

Mit Einführung der automatischen Übersetzung von Germanized über das GlotPress-Repository, wurde die Möglichkeit des Überschreibens der Übersetzungen im language-Ordner "geraubt". Übersetzungen werden nun wieder zuerst im Ordner wp-content/languages/woocommerce-germanized gesucht und geladen.

mmh. den Ordner gibt es nicht.
Hätte zur Auswahl: /wp-content/languages/plugins
/web/wp-content/languages
wobei mir /wp-content/languages/plugins lieber ist, da übersichtlicher

**Comment by vendidero** [comment]
Hi,

den Ordner musst du selbst anlegen. Der /plugins/ Ordner eignet sich nicht, da WP dort die "automatischen" Updates der Sprachdateien speichert.
