### ISSUE TITLE
Falsche Anzeige v. Nachrichten nach Registrierung?

### ISSUE THREAD

**Issue by phreaks** [vendidero/woocommerce-germanized#41]
Voreinstellungen:
- Gast-Checkout ist deaktiviert
- Double Opt-In ist aktiviert

Ablauf:
1. Bei Checkout erfolgt redirect auf Account-Seite mit Hinweis: "Bitte erstelle ein Kundenkonto oder logge dich ein, bevor du zur Kasse gehst"
2. Es wird ein Konto angelegt. Es folgt ein redirect wieder auf die Account-Seite. Nun werden 2 Hinweise angezeigt:
"Bitte aktiviere dein Kundenkonto indem du auf den Link in der E-Mail klickst." und
"Bitte erstelle ein Kundenkonto oder logge dich ein, bevor du zur Kasse gehst"

Müsste es nicht so sein, dass die 2. Notice bei Punkt 2 nicht mehr angezeigt werden sollte?

Hier die relevante Methode mit einer Ergänzung (return):
```
public function show_disabled_checkout_notice() {

		if ( ! is_user_logged_in() && isset( $_GET[ 'account' ] ) && 'activate' === $_GET[ 'account' ] ) {
			wc_add_notice( __( 'Please activate your account through clicking on the activation link received via email.', 'woocommerce-germanized' ), 'notice' );
            return;
		}

		if ( is_account_page() && WC()->session->get( 'login_redirect' ) ) {

			if ( ! is_user_logged_in() ) {

				if ( get_option( 'woocommerce_enable_guest_checkout' ) === 'yes' ) {
					wc_add_notice( sprintf( __( 'Continue without creating an account? <a href="%s">Click here</a>', 'woocommerce-germanized' ), add_query_arg( array( 'force-guest' => 'yes' ), wc_gzd_get_page_permalink( 'checkout' ) ) ), 'notice' );
				} else {
					wc_add_notice( __( 'Please create an account or login before continuing to checkout', 'woocommerce-germanized' ), 'notice' );
				}

			} else {

				// Redirect to checkout
				wp_safe_redirect( wc_gzd_get_page_permalink( 'checkout' ) );
				exit;

			}

		}

	}
```

**Comment by vendidero** [comment]
Hi,

stimmt, das wäre besser. Habe ich gerade commited..
Danke!
