### ISSUE TITLE
Amazon Payments Advanced & Mehrstufige Kasse

### ISSUE THREAD

**Issue by dfarin** [vendidero/woocommerce-germanized#44]
https://github.com/vendidero/woocommerce-germanized/issues/36
Kann es sein das es hier immer noch Probleme gibt?
Ich habe das gerade mit der Version 1.5.7 und dem gleichen Plugin versucht, der Checkout Prozess bricht immer noch ab wenn Amazon als Zahungsvariante genutzt wird.

Bei mir zumindest musste ich die mehrstufige Kadde ausstellen damit ich Amazon Payments nutzen konnte.

**Comment by vendidero** [comment]
Hi,

das schaue ich mir mal an - wir hatten aber eine Kompatibilität hergestellt. Welches Plugin verwendest du dort genau (genauer Name + Version)?

Grüße

**Comment by dfarin** [comment]
Hey Dennis, das gleiche Plugin, also das
https://woocommerce.com/products/pay-with-amazon/
in Version 1.6.1
über Schritt 2 gehts nicht hinaus.

Gruß
Dennis

**Comment by vendidero** [comment]
Hi,

also mir liegt hier nur v. 1.2.1 des Plugins vor und damit konnte ich keine Probleme feststellen. Sende mir doch mal eine E-Mail an info@vendidero.de - dann können wir das bestimmt klären.

Grüße

**Comment by dfarin** [comment]
Hey Dennis, Mail angekommen?

**Comment by vendidero** [comment]
Hi,

ja, habe ich. Diese Schlauberger habe die Plugin-Datei umbenannt (von amazon-payments-advanced.php in woocommerce-gateway-amazon-payments-advanced.php) - deshalb lädt Germanized die entsprechende Kompatibilitäts-Klasse nicht. Ich werde das im nächsten Release anpassen. Solange könntest du theoretisch die Plugin-Datei wieder umbenennen, sodass Germanized Pro sie wieder erkennt.

Grüße

**Comment by dfarin** [comment]
Ja, das AMAPAy ist nicht optimal.. der Pay with button wird auch ekelhaft plätziert, aber ok, danke für den Hinweis.
