### ISSUE TITLE
Tax issue on mobile

### ISSUE THREAD

**Issue by Fusaro1** [vendidero/woocommerce-germanized#45]
Hi,
in my shop the prices for all of the products are ok, like I set them. But on the same shop with the same products on my mobile there are other prices. I calculated that on every price there is a reduction of 26%. I think that this means that the software takes the German VAT (19%) and reduced VAT (7%).
I hope you can help me here.

**Comment by vendidero** [comment]
Hi there,

we are not calculating any taxes except some improved shipping taxation.
Seems like your tax rules are being messed up. You may contact the WooCommerce Support or check your settings. You may delete your session/cookies to not be misrouted by outdated data.

cheers
