### ISSUE TITLE
WooCommerce template files

### ISSUE THREAD

**Issue by Ninos** [vendidero/woocommerce-germanized#47]
Hey there,
can you guys may send me a list which woocommerce template files get overwritten by your own template files? My problem is that you're listing also woocommerce-germanized template files in following folder, so I cannot seperate the woocommerce and woocommerce-germanized template files:
https://github.com/vendidero/woocommerce-germanized/tree/master/templates

PS: I'm a theme dev and want to support germanized by default. Therefor I need the list to know which files I need to check :)

**Comment by vendidero** [comment]
Hi there,

the only template we do override is:
woocommerce-germanized/templates/checkout/terms.php

We do extend the default WooCommerce template "checkout/review-order.php" by adding sub templates called "review-order-product-table.php" and "order-submit.php" which we save in:

woocommerce-germanized/templates/checkout/review-order-product-table.php
woocommerce-germanized/templates/checkout/order-submit.php

cheers

**Comment by Ninos** [comment]
Perfect, thx. Then I'll try to do my theme compatible with your plugin. Seems you guys removed some dependencies the last months :)
