### ISSUE TITLE
remove title and VAT-ID from formatted_billing_address

### ISSUE THREAD

**Issue by benjamindahl** [vendidero/woocommerce-germanized#49]
I wanted to remove the formatted_address_replacements »title« and »vat-id« from the address field on the invoice. How is this to be done? I'm quite unexperienced with php and wordpress but still like to ask.

Current code is like this:

![bildschirmfoto 2017-02-24 um 17 56 10](https://cloud.githubusercontent.com/assets/2698024/23312579/94596bfe-faba-11e6-805e-a55092eed4af.png)

Result looks like this currently:

![bildschirmfoto 2017-02-24 um 17 52 24](https://cloud.githubusercontent.com/assets/2698024/23312429/062b3ede-faba-11e6-8639-e367469d2c0b.png)

Cheers

B

**Comment by vendidero** [comment]
Hi there,

well, the address is formatted by WooCommerce - and outputted by $invoice->get_address() (as seen above). You may see woocommerce/includes/abstracts/abstract-wc-order.php "get_formatted_billing_address" - you can use the filter:

```php
// Formatted Addresses.
$address = apply_filters( 'woocommerce_order_formatted_billing_address', array(
	'first_name'    => $this->billing_first_name,
	'last_name'     => $this->billing_last_name,
	'company'       => $this->billing_company,
	'address_1'     => $this->billing_address_1,
	'address_2'     => $this->billing_address_2,
	'city'          => $this->billing_city,
	'state'         => $this->billing_state,
	'postcode'      => $this->billing_postcode,
	'country'       => $this->billing_country
), $this );
```

to adjust the output. Use a high priority within add_filter (https://developer.wordpress.org/reference/functions/add_filter/) to make sure, you are the "last" one manipulating the array. This will only work for new invoices generated though.

cheers

**Comment by benjamindahl** [comment]
Thanks for your help. I could solve the problem by adding the following code to the template

`<?php
//custom formatted address
$document_address = apply_filters( 'woocommerce_order_formatted_billing_address', array(
				'title'			=> '',
				'first_name'    => $order->billing_first_name,
				'last_name'     => $order->billing_last_name,
				'company'       => $order->billing_company,
				'address_1'     => $order->billing_address_1,
				'address_2'     => $order->billing_address_2,
				'city'          => $order->billing_city,
				'state'         => $order->billing_state,
				'postcode'      => $order->billing_postcode,
				'country'       => $order->billing_country,
				'vat_id'		=> '',
			), $invoice );
			
$document_formatted_address = WC()->countries->get_formatted_address( $document_address );
?>
<?php if ( $document_formatted_address ) : ?>
	<?php $pdf->writeCustomHTML( wpautop( $document_formatted_address ), array( 'classes' => array( 'address' ) ) ); ?>
<?php endif; ?>`



Cheers.

Benny
