### ISSUE TITLE
Please add source map files for .min.js and css files for easier debugging on live system

### ISSUE THREAD

**Issue by gerdneuman** [vendidero/woocommerce-germanized#50]
For debugging https://wordpress.org/support/topic/markup-anderung-zw-1-7-und-1-8-1-notwendig/ I had to install on a test system and define `SCRIPTS_DEBUG`. This would have been easier if there were source map files for minified js and css files, because then debugging could have been done on the live system.

Adding source maps is just an option to uglify js and cssmin in the Gruntfile, so should be easy and adds a real improvement on debugging live systems:
* https://github.com/gruntjs/grunt-contrib-uglify#sourcemap
* https://github.com/gruntjs/grunt-contrib-cssmin#sourcemap

**Comment by vendidero** [comment]
Hi there,

I think it is not really necessary - we have SCRIPT_DEBUG (just like WooCommerce does it) and we have the unminified files. I don't think we'll need to store another file within the repo.
