### ISSUE TITLE
Emails about Completed Orders When aborting PayPal payment

### ISSUE THREAD

**Issue by bobmosh** [vendidero/woocommerce-germanized#51]
Hey,

I noticed that when using PayPal, the notification emails about the order get sent as soon as I get redirected to pay via PayPal.
If I follow the abort link back to the Order Page, the email is already out and looks like it is paid (which obviously it is not).

If I turn of WooCommerce Germanized as a plugin, everything works as expected, but as soon as the plugin is activated the issue occurs.

Is this a planned behaviors or is this a bug?

Cheers,
Ferdinand

**Comment by vendidero** [comment]
Hi,

this is expected behavior to meet german law. You may find more information about this topic in this thread (german):
https://wordpress.org/support/topic/bestellbestatigung-und-paypal-plus/

cheers

**Comment by nicmare** [comment]
what is the filter/code to change this behavior back to regular? i know you and trusted shop don't want this and you don't give support with this but i will do it in my own responsibility.

**Comment by vendidero** [comment]
Hi there,

check the filter here: https://gist.github.com/vendidero/01d28cba32c20e4a7a308eb4bf86de3e

Cheers

**Comment by nicmare** [comment]
thank you!
