### ISSUE TITLE
Error in translation of small business notice in latest update

### ISSUE THREAD

**Issue by tilmanbremer** [vendidero/woocommerce-germanized#53]
Hi,
I noticed that the small business notice is not translated on the frontend. It seems like it changed to 
`Value added tax is not collected, as small businesses according to §19 (1) UStG.` in the latest update,
yet in includes/wc-gzd-functions.php in line 94 the english term is different. 

I tried to adjust the term in the file includes/wc-gzd-functions.php, but it didn't help. Also, the option in the backend to adjust the small business notice seems to have no effect anymore. It worked in earlier versions.

Also, the english term is not really a sentence.

Tested with woocommerce 3.0.1, wcg 1.8.8 and WP 4.7.3

**Comment by vendidero** [comment]
Hi there,

seems like you are using WPML? You may check the string translation feature to translate that string. In wc-gzd-core-functions.php `wc_gzd_get_small_business_notice` returns just what you have quoted above (Value added tax is not collected, as small businesses according to §19 (1) UStG.).

cheers

**Comment by tilmanbremer** [comment]
Oh sorry, forgot to mention that. I am using `qTranslate-X` and the `WooCommerce & qTranslate-X` Plugin.

That is weird. I updated to the last version of wc-gzd, but the term in `wc_gzd_get_small_business_notice` was in fact different.

What I don't understand, why it is not translating now. The term is correct, the translation of that term can be found in `plugins/woocommerce-germanized/i18n/languages/woocommerce-germanized-de_DE.po`, but it still shows in English in the Shop when the frontend is set so German. Everything else is translated.

I tried to set the custom notice in the wc-gzd backend to a qTranslate-X style term: `[:en]Value added tax is not collected, as small businesses according to §19 (1) UStG.[:de]Kein Mehrwertsteuerausweis, da Kleinunternehmer nach §19 (1) UStG.[:]`, but shows no difference in the frontend.

Don't get me wrong, I am not trying to get free support, I am just trying to figure out if it is a bug or not. Also I am trying to figure out what plugin is causing this. For example, it feels like the custom notice field from the backend ist not used at all, is that possible?

**Comment by vendidero** [comment]
Hi there,

yes, the term is included in the language files - but is only used as a fallback if the option "woocommerce_gzd_small_enterprise_text" returns nothing at all (does not exist) in the wp_options table. That's the way Germanized handles other user-chooseable terms as well (like the delivery notice text). I don't know whether qtranslate offers a way (like WPML) to translate strings from wp_options table. 

cheers
