### ISSUE TITLE
mini_desc über die REST API

### ISSUE THREAD

**Issue by Babelfisch** [vendidero/woocommerce-germanized#56]
Mit bc66c5400ce378f080a91950a5787aa78bcc097e wurde ergänzt, dass `mini_desc` jetzt über die REST API gespeichert werden kann. Beim Speichern werden mit `sanitize_text_field` aber sämtliche HTML-Tags und Zeilenumbrüche entfernt. Die sind jedoch in der Warenkorb Kurzbeschreibung erlaubt und erwünscht.

**Comment by vendidero** [comment]
Danke, da fehlte das esc_html for dem sanitizing 👍

**Comment by Babelfisch** [comment]
Supi! Allerdings bleiben Shortcodes nicht erhalten und werden „geparst“ gespeichert. Kann man die irgendwie auch „retten“. Bei den normalen Feldern wie `description` oder `short_description` bleiben Shortcodes erhalten.

**Comment by vendidero** [comment]
Das ist jetzt grundsätzlich erst einmal nicht angedacht. Es gibt aber einen Filter "woocommerce_gzd_product_cart_description" - da kannst du evtl. etwas mit do_shortcode (https://developer.wordpress.org/reference/functions/do_shortcode/) machen.

**Comment by Babelfisch** [comment]
Ich glaube nicht, dass mir das weiterhilft. Ich will ja in der Kurzbeschreibung permanent einen Shortcode (bspw. `[license-text]`) speichern, damit ich bei Änderungen des Textes nicht jedes Produkt wieder anfassen muss. In `mini_desc` wird jetzt aber nach dem Anlegen des Produkts über die REST API der Lizenztext direkt gespeichert, wohingegen bei den WC-eigenen Feldern wie `description` der Shortcode erhalten bleibt.

**Comment by vendidero** [comment]
Hm, ich habe das auch gerade mal getestet und ich kann Shortcodes problemlos über die REST API in der mini_desc speichern. Es werden im Code ja auch nirgends Shortcodes explizit "ausgeführt", d.h. das einzige was passiert ist:

`$data['_mini_desc'] = sanitize_text_field( esc_html( $request['mini_desc'] ) );`

**Comment by Babelfisch** [comment]
Grrr, du hast Recht. Weil das vorher ja nicht funktioniert hat, hatte ich dort noch eine alte Beschreibung ohne Shortcode gesetzt und dachte dann, dass `sanitize_text_field` auch die Shortcodes mit umwandelt. Mein Fehler.

Jetzt passt alles!
