### ISSUE TITLE
permanent-hide-invoices-invoice-cancel-box-via-screen-settings

### ISSUE THREAD

**Issue by Tobias-Conrad** [vendidero/woocommerce-germanized#57]
thanks a lot for the nice plugin. ;-)

https://wordpress.org/support/topic/permanent-hide-invoices-invoice-cancel-box-via-screen-settings/

at the moment i hide the invoices”, “invoice cancel” box via screen settings in the upper right on the invoice edit page. as you see in the picture it only hides a unique invoice, so the next order the two boxes are viewed again and at the top.

Please see picture: http://www.awesomescreenshot.com/image/2452674/ca8ce89704177ebcc88c5f6dd9f5fe39

Thanks for solving.

Also not possible to change order of the boxes permanetly.

**Comment by vendidero** [comment]
Hi there,

yes, I somewhat forgot about that problem. I've got it on the roadmap now for the next Version of Germanized Pro. Thanks for reporting again :)

**Comment by Tobias-Conrad** [comment]
not fixed. sorry. i love your plugin. please look again at the screenshot attached:
May mark the code changes here in ticket. may they are not included in the new version?
Version 1.8.0 + Version 1.8.11 and WOO 3.0.9 und ngnix server mit flatsome theme.
![rechnungen ausblenden](https://user-images.githubusercontent.com/7352673/27540409-6667767a-5a80-11e7-9c9a-f939fe52e172.png)

**Comment by Tobias-Conrad** [comment]
@vendidero please see screenshot above

**Comment by vendidero** [comment]
Hi,

the "title" remained the same but the container-id is now a consecutive number. If you hide the "first" invoice with the title "2017-Rechnung 313" all other "first" invoices will be hidden too - please check that while editing another order.

**Comment by Tobias-Conrad** [comment]
ok. thanks

**Comment by Tobias-Conrad** [comment]
it is not fixed in new orders allways show Rechnung, also on mobile view. 
please review. may not added code in the lastest version.

**Comment by Tobias-Conrad** [comment]
okay. when i save order after change order to completed Rechnungen/invoices are shown again.

**Comment by Tobias-Conrad** [comment]
so after i got an invoice number it always shows. 
solution: please do not use the invoice number for headline section and for the "screen options" just invoice and invoice storno

**Comment by Tobias-Conrad** [comment]
also rechnung is shown on top of every new order
