### ISSUE TITLE
mini_desc ist nicht mehr mehrzeilig

### ISSUE THREAD

**Issue by Babelfisch** [vendidero/woocommerce-germanized#58]
In #56 gab es ja den Fix für die Warenkorb-Kurzbeschreibung `mini_desc` für die REST-API. In diesem Zug wurde in der `class-wc-gzd-meta-box-product-data.php` auch ein `sanitize_text_field` beim Speichern im Editor eingebaut – mit dem Ergebnis, dass die Kurzbeschreibung jetzt nicht mehr mehrzeilig sein kann und alle Zeilenumbrüche in `&nbsp;` umgewandelt werden.

Egal ob im visuellen oder Texteditor, beim Speichern stehen alle Absätze hintereinander, da WP ja Absätze nicht in `<p>` speichert.

Das war doch sicherlich nicht so beabsichtigt?

**Comment by vendidero** [comment]
Hi,

nein, das war natürlich nicht gewünscht. Ich habe das gerade mal gefixt. Danke für die Meldung.
