### ISSUE TITLE
woocommerce-germanized-pro guest-id on packing-slip

### ISSUE THREAD

**Issue by Hermsi1337** [vendidero/woocommerce-germanized#59]
Hey m8,

were using the pro-version of your germanized plugin and currently doing some adjustment.

While printing packing-slips for guest-orders we noticed, that the customer-id is empty.
If you print an invoice for guest-orders the customer-id looks like this: B-$order_id

I did some research but TBH I did not find the place where you get the customer_id.
In table.php you call get_static_pdf_text which is defined in abstract-wc-gzdp-post-pdf.php.
But if I do a var_dump on the $invoice or $order object, I get several information but not the customer_id.

For clarification I got you two screenshots...
... one for invoice
![inv](https://user-images.githubusercontent.com/16942003/27508436-218051cc-58e5-11e7-9fbb-48997c2b8bb9.JPG)

... and one for packing-slip
![ps](https://user-images.githubusercontent.com/16942003/27508437-2b643fe6-58e5-11e7-9676-78b055d3fbe2.JPG)

Could you give me a hint on how to add the customer_id to packing slip for guest-orders?

Thank you!

**Comment by vendidero** [comment]
Hi there,

for guest-checkouts there is no customer_id/user_id because no user account is being registered.
How do you implement the customer number you are talking about? So what does your static settings text look like? 

cheers

**Comment by Hermsi1337** [comment]
Hey,

thank you for taking time.
I guess I did not explain my "problem" enough.

My problem basically is the following:
Why there is a customer-id for guests on the invoice, but not on the packing-slip?
I would like to print the same customer-id on packing-slip as shown on invoice.

The function which adds the header to the pdf is the same in both cases.
Is it simply a setting in backend which allows me to display a customer-id for guest orders on packing slips?

Regards

**Comment by vendidero** [comment]
Hi,

how did you implement the customer-id show-up in the invoice? Did you use a Shortcode from here: 
https://vendidero.de/dokument/shortcodes-fuer-rechnungen

If possible please describe your problem again in german to make sure we are talking about the same problem :)

cheers

**Comment by Hermsi1337** [comment]
Gute Idee 😆 

Es geht konkret um die Erstellung von Lieferscheinen und Rechnungen.
Wenn ich die Rechnung für eine Gastbestellung generiere, wird die Kundennummer ausgefüllt - siehe Screenshot.
Generiere ich aber einen Lieferschein für eine Gastbestellung, bleibt die Kundenummer auf diesem Lieferschein leer.

Das Template für die Generierung entspricht so ziemlich dem mitgelieferten Default-Template, mit ein paar kleinen Anpassungen an den Spalten.

Wenn ich das richtig interpretiere, wird die Kunden-Nummer und alles übrige im Header mit der folgenden Funktion generiert:
```php
<?php if ( $invoice->get_static_pdf_text( 'before_table' ) ) : ?>
	<div class="static">
		<?php echo $invoice->get_static_pdf_text( 'before_table' ); ?>
	</div>
<?php endif; ?>
```

Diese Anweisung steht sowohl im Template für die Rechnung, als auch im Template für die Lieferscheine.
Kommentiere ich sie aus, fehlt der ganze Kopfbereich, daher meine Vermutung dass dieser Teil dafür verantwortlich ist. ^^

Kannst du mir sagen, inwiefern sich der Lieferschein von der Rechnung unterscheidet?
Gibt es extra Parameter die abgefangen werden müssen? Fehlt einfach eine Einstellung im Backend?

Ich hoffe, jetzt verstehen wir uns besser. 🤣 

Vielen Dank und liebe Grüße
Dennis

**Comment by vendidero** [comment]
Hi,

naja, es wäre immer noch interessant zu sehen, welchen Shortcode du in den Einstellungen von Germanized (Rechnungen & Lieferscheine) verwendest um die Kundennummer zu erzeugen? Der Shortcode dürfte ja im Einstellungs-Text "Vor der Tabelle" erscheinen. 

Grüße

**Comment by Hermsi1337** [comment]
Hey,

im "Before table" steht gar nichts drin.

Daher verstehe ich leider überhaupt nicht, wie genau sich die Adresse zusammensetzt.
Welche weiteren Infos brauchst du? Dann lasse ich dir das mal über das Vendidero Ticketsystem zukommen.

Ich dachte nur es wäre ein "grundsätzliches" Problem, daher das issue hier auf Github.

Danke und Gruß

**Comment by vendidero** [comment]
Ich denke dann kann das nur über einen Filter eingefügt worden sein:
woocommerce_gzdp_pdf_static_content
Danach solltest du mal suchen. Alternativ solltest du mal Testausgaben in:
woocommerce-germanized-pro/includes/abstract/abstract-wc-gzdp-post-pdf.php
in der Methode "get_static_pdf_text" machen (und eine Testrechnung generieren).

Grüße

**Comment by Hermsi1337** [comment]
Okay, vielen Dank für deine Unterstützung!

Ich schaue dann mal weiter.
