### ISSUE TITLE
Tax for Zahlungsgebühr not considered

### ISSUE THREAD

**Issue by daniel-koertvelyessy** [vendidero/woocommerce-germanized#62]
Hallo !

Bei der Zahlungsgebühr kann die Berechnung der MwSt. für die Gebühr aktiviert werden. Jedoch scheint sich diese nicht bei der Berechnung im Warenkorb oder in der Kasse auszuwirken. z.B. bleiben 2EUR Zahlungsgebühr immer 1,68 EUR.

Ist das ein Bug oder meine falsche Anwendung?

LG Daniel

Dann wäre es noch nett, wenn ein Dropdown kommen könnte, ob die Gebühr fest oder prozentual berechnet wird (z.B. 1,8% bei PayPal)

-----------------------------------------------------------------------------------------------
There is a option to calculate the tax on the payment charge, however it does not seem to do the actual calculation in the card of checkout page. E.g. a 2.0 EUR payment charge is displayed as 1.68 EUR regardless of the checkbox activated in the BE or not.

**Comment by vendidero** [comment]
Hi,

ich denke mal das hat dann eher etwas mit deinen Woo-Steuereinstellungen zu tun. Du müsstest mal deine Steuersätze entsprechend kontrollieren.

Grüße
