### ISSUE TITLE
Subscriptions Renewal

### ISSUE THREAD

**Issue by F4bsi** [vendidero/woocommerce-germanized#64]
Hey,

ich habe gerade die neue Funktion für das Abonnement mit den Lastschriften getestet (4fdb662 ), und mir ist dabei aufgefallen, dass bei der automatischen Verlängerung keine neue Bestellung erstellt wird und aus dem Abonnement alle Zahlungsdaten außer der Mandat ID gelöscht werden. 

Wenn ich im Gateway unter $this->supports = array( den Wert 'gateway_scheduled_payments' entferne, funktioniert es anscheinend wieder wie gewohnt.  Liegt der Fehler irgendwo auf meiner Seite, oder habe ich irgendwas übersehen?

Danke und viele Grüße

**Comment by vendidero** [comment]
Hi,

die Funktion ist gerade noch in der Beta-Phase. Ich werde wohl noch einige Dinge verbessern/testen müssen. Offenbar ist das nicht ganz so einfach. Wir arbeiten gerade im Rahmen dieses Pull Requests an dem Thema (https://github.com/vendidero/woocommerce-germanized/pull/63). Du kannst dich gerne an der Diskussion beteiligen.

Grüße
