### ISSUE TITLE
manual added orders' customers do not get vat id field filled

### ISSUE THREAD

**Issue by x-moe-x** [vendidero/woocommerce-germanized#65]
adding a new Order via `wp-admin/post-new.php?post_type=shop_order ` results in an empty vat id field although there's a vat id configured for this customer.

I suggest using `woocommerce_ajax_get_customer_details` to filter customer details and inject vat id to profit from `meta-boxes-order.js` autofill mechanism

**Comment by vendidero** [comment]
Hi,

thanks for the report. Will be added upon next release.

Cheers
