### ISSUE TITLE
Bestelldetails und Email zeigt Anzahl 0

### ISSUE THREAD

**Issue by winedata** [vendidero/woocommerce-germanized#66]
Bei neuen Bestellungen wird seit kurzem (1.9.5?) die Bestellmenge in der Zusammenfassung nicht mehr richtig ausgegeben und nur 0 angezeigt, auch in den Bestätigungsemails an die Kunden.

![grafik](https://user-images.githubusercontent.com/33560169/32682846-a13fc58c-c677-11e7-955c-350af2d8fa5d.png)

**Comment by vendidero** [comment]
Hi,

ich denke das ist eher ein Problem mit irgendeinem Drittanbieter Plugin - Germanized hat mit den Stückzahlen nichts zu tun. Auch die Bestellbestätigung ist eigtl. ein Standard-WooCommerce-Template (customer processing order email) - oder ist das Problem behoben, wenn du Germanized deaktivierst?

Grüße
