### ISSUE TITLE
PayPal Express Checkout

### ISSUE THREAD

**Issue by Babelfisch** [vendidero/woocommerce-germanized#68]
Durch das zusätzliche Feld _Anrede im Checkout_ funktioniert die Zahlung über das Plugin _WooCommerce PayPal Express Checkout Gateway_ nicht. Nach der Zahlung kommt die Fehlermeldung _Rechnung Anrede ist ein Pflichtfeld_.

Man kann das Feld zwar ausblenden, da die Anrede aber durchaus nützlich ist, wäre es in meinen Augen sinnvoller, es einfach nur _nicht_ als Pflichtfeld zu definieren. Beim manuellen Checkout muss es sowieso ausgefüllt werden und beim PayPal Express steht dann eben nichts drin, was nicht weiter tragisch ist.

**Comment by vendidero** [comment]
Hi,

hm, das ist wahrlich nicht so schön. Komisch, dass solche Dinge nicht vom Gateway Plugin vorgesehen sind - das wird ja u.U. auch auf andere Felder zutreffen, die von Drittanbieter-Plugins hinzugefügt werden. Ich werde mal sehen, ob es Sinn macht, das Feld als nicht-Pflichtfeld zu markieren - danke für den Hinweis.

**Comment by Babelfisch** [comment]
Die Frage ist jetzt schon lange geschlossen aber leider noch nicht gelöst, oder? Ohne eigene Programmierung über einen Hook lässt sich Gemanized mit dem Feld für Anrede nicht mit PayPal Express nutzen. Gibt es dazu was neues?
