### ISSUE TITLE
WP_Cart->taxes is deprecated

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [vendidero/woocommerce-germanized#69]
Hello!

Thank you for the cool plugin.

```log
PHP message: The WC_Cart->taxes function is deprecated since version 3.2. Replace with getters (WC_Cart::get_cart_contents_taxes()) and setters (WC_Cart::set_cart_contents_taxes())
````

Since we updated to WooCommerce 3.2 we are getting the message above - maybe you should keep it mind for the next update.

Cheers,
Rado

**Comment by vendidero** [comment]
Hi,

thanks for the hint - I'll fix that upon the next release..
