### ISSUE TITLE
For orders with products that have 7% and 19% taxes only 19% is shown on cart page

### ISSUE THREAD

**Issue by heynad** [vendidero/woocommerce-germanized#7]
See this screenshot, the 1st product is 7% (food) and the second is 19%

![selection_005](https://cloud.githubusercontent.com/assets/11075318/6286959/75819f8a-b90d-11e4-9d69-d1a3c6b624eb.png)

After removing the 2nd 19% product, it's ok:
![selection_006](https://cloud.githubusercontent.com/assets/11075318/6286981/b4bf5160-b90d-11e4-801b-0d1fd408d2cc.png)

For orders with 7% and 19% both tax classes must be shown.

As our shop has products with 7 and 19% this is a business critical feature for us.

**Comment by vendidero** [comment]
Works quite well if you setup your shop correctly. Might need to set tax option from "single" to "itemized" (see WooCommerce Settings > Tax > Tax total display)

**Comment by heynad** [comment]
I hope you do not mind switching to German as the upcoming screenshots are as well ;)

Bei mir ist es so eingestellt:
![selection_008](https://cloud.githubusercontent.com/assets/11075318/6287212/150c06d8-b910-11e4-9551-0f6af75a3ebe.png)

Bei 7% sieht es so aus:
![selection_009](https://cloud.githubusercontent.com/assets/11075318/6287217/2899350e-b910-11e4-8960-bcb5638963f3.png)

Bei Standard (19%) so:
![selection_010](https://cloud.githubusercontent.com/assets/11075318/6287221/3c5d9c1a-b910-11e4-8d15-c927584d99c6.png)


Hmh, vllt. übersehe ich was, aber sieht erst mal richtig aus. 

Dennoch wird immer nur der Steuersatz des /letzten/ Produktes genommen. Ist das 7% (hier mal beide Produkte in Reihenfolge getauscht), dann ist auch die Auflistung nur 7%, nicht nur im Warenkorb sondern auch in der Übersicht bei Kasse:
![selection_011](https://cloud.githubusercontent.com/assets/11075318/6287321/e8d6421c-b910-11e4-9bd3-28f5408c68de.png)

**Comment by vendidero** [comment]
Hi,

scheint wohl daran zu liegen, dass du beide MwSt.-Sätze gleich benannt hast. WooCommerce zieht diese MwSt.-Sätze dann automatisch zusammen - dadurch entsteht dieses Missverständnis. Ich werde mal schauen ob es Sinn macht, dieses Verhalten zu unterbinden. Solange benenne doch bitte den 7%-Satz um in z.B. "MwSt. 7%" - das erscheint ja eh nicht im Frontend.

**Comment by heynad** [comment]
Jepp, nachdem umbenennen geht es. Danke. 

Diese komische Bennnung hat mir afaicr WooCommerce German Market so eingerichtet :-/ 

Ich lass das Ticket mal offen, falls du noch das Verhalten standardmäßig unterbinden willst. Ansonsten kann es von mir aus auch geschlossen werden. Nochmals Danke!

**Comment by heynad** [comment]
Wo es hingegen nicht funktioniert, ist wenn man Bestellungen manuell im Backend erfasst (WC > Bestellungen > Bestellung hinzufügen). Wir nutzen das relativ häufig, weil es auch Bestellungen per Telefon u.ä. gibt. 

Wenn man da zuerst "Versandkosten hinzufügen" und dann "Steuern berechnen", funktioniert das nicht.

Ist für uns jetzt nicht so schlimm, weil wir können aus einer Bestellung aus 7% und 19% auch zwei getrennte Bestellungen machen (workaround) wo der MwSt-Anteil ja dann immer fix ist. Ich wollte es aber nur mal anmerken, weil ich das prinzipiell für einen Bug halte. 

Evtl. müsste man hier auch her bei WC direkt ein Ticket aufmachen, weil dass im Backend mit Netto gearbeitet wird, obgleich man in den WC-Einstellungen Brutto gewählt hat, finde ich auch schon "schwierig" und muss ich den KollegInnen immer wieder erklären.

**Comment by vendidero** [comment]
Hi,

ich habe das gerade mal getestet und bei mir funktioniert das problemlos (wenn ich manuell Produkte mit 7% bzw. 19% hinzufüge, werden diese MwSt.-Sätze auch getrennt berechnet, wenn man auf "Steuern berechnen" klickt). Das einzige, das nicht richtig funktioniert, ist das automatische splitten der MwSt. für Versandkosten.

**Comment by heynad** [comment]
Hallo!

Ach so ja, sorry, genau das meinte: Das Aufsplitten der Mehrwertsteuer bei Versandkosten funktioniert nicht. Aber wie gesagt, dass kann man auch über einen Workaround dann lösen, indem man einfach 2 Rechnungen drausmacht.
