### ISSUE TITLE
E-Mail: Benutzerkonto aktivieren Link ohne Aktivierungscode 

### ISSUE THREAD

**Issue by NN01010101** [vendidero/woocommerce-germanized#70]
Wenn in W3 Total Cache Plugin die Option "Database Cache" aktiviert ist, kommt bei neuer Regestrierung die Mail mit dem Aktivierungs-Link ohne den Key an:
https://example.com/my-account/?activate
statt
https://example.com/my-account/?activate=$P$BtsweqAzpstY3lBaq1tsAwBGgweq/S11

Ich nehmen an man muss bei den W3TC unter "Database Cache Settings" im Feld "Ignored query stems" einen Query String von Woocommerce Germanized eintragen. 
Welcher ist es denn?
Vielen Dank im Voraus

**Comment by vendidero** [comment]
Hi,

wir verwenden für den Aktivierungs-Key den meta_key "_woocommerce_activation" in der usermeta-Tabelle. Da wir das Problem aber häufiger berichtet bekommt, habe ich da jetzt eine kleine Implementierung hinzugefügt die aktuell zumindest W3 Total Cache unterstützt:
https://github.com/vendidero/woocommerce-germanized/commit/c65b74b782e134344a6ef0254877125534af456e

Grüße
