### ISSUE TITLE
HTTPS-Link Link zur OS-Plattform

### ISSUE THREAD

**Issue by r-brown** [vendidero/woocommerce-germanized#71]
Hallo,

Könnt ihr bitte HTTPS-Link Link zur OS-Plattform bei `gzd_complaints` shortcode updaten.
Also: https://ec.europa.eu/consumers/odr

VG

**Comment by vendidero** [comment]
Hi,

ja, das habe ich schon auf dem Zettel. Dazu gibt es heute ein Update :)
