### ISSUE TITLE
Bei Bestellung auf Vorkasse wird "customer-processing-order" Template verschickt statt "customer-on-hold-order"

### ISSUE THREAD

**Issue by TomKnox** [vendidero/woocommerce-germanized#72]
Wenn der Kunde Überweisung auswählt wird der Status On Hold gesetzt es wird jedoch die Email in Bearbeitung verschickt.

**Comment by vendidero** [comment]
Hi,

das haben wir relativ häufig diskutiert. Germanized versendet genau eine Bestellbestätigung-Mail (unabhängig von der Zahlungsmethode). Dabei handelt es sich um das Template "customer-processing-order". Dieses Vorgehen haben wir mit Trusted Shops abgesprochen und für sinnvoll befunden. Du kannst theoretische das automatische Versenden von Bestellbestätigungen in Germanized deaktivieren (s.h.  https://github.com/vendidero/woocommerce-germanized/blob/master/includes/wc-gzd-core-functions.php#L19)

Grüße
