### ISSUE TITLE
Why do you hide variation price?

### ISSUE THREAD

**Issue by crstnio** [vendidero/woocommerce-germanized#74]
**add-to-cart-variation.js**

```js
if ( variation.price_html !== '' ) {
	$( '.single_variation .price' ).hide();
	$wrapper.find( '.price:not(.price-unit):first' ).html( variation.price_html ).addClass( 'variation_modified' );
	$wrapper.find( '.price:not(.price-unit):first' ).find( '.price' ).contents().unwrap();
}
```

Is there a good reason to hide `.single_variation .price`? I want to display it according to the WooCommerce default.

It took me some time to find this ~~bug~~ feature in your plugin.

**Comment by vendidero** [comment]
Hi there,

we do hide the default variation price because we replace the variable price with the variation price.
That is done to make sure that we are showing the concrete price only (with the appropriate price labels e.g. VAT and shipping cost notice).

Cheers
