### ISSUE TITLE
Chrome Console Error on Checkout page: "Found 2 elements with non-unique id #_wpnonce"

### ISSUE THREAD

**Issue by gerdneuman** [vendidero/woocommerce-germanized#75]
I see on my test server when going to the checkout this Error is reported in the Chrome Console:

![image](https://user-images.githubusercontent.com/12525563/37760524-3ac5ccbe-2db7-11e8-8068-330388fb971a.png)

The more info link points to: https://www.chromium.org/developers/design-documents/create-amazing-password-forms

I reported this first to our Theme Developer (Pinnacle Premium) and he said it would be a bug/problem coming from Germanized plugin:

> The warning about the #id being called twice I think if your Germanized woocommerce plugin. From what I can see by viewing source when the page loads there are two place order buttons and two _wpnounces added to the page, then javascript (which I believe comes from Germanized woocommerce plugin) removed the first because it’s adding the second.

**Comment by vendidero** [comment]
Hi there,

yes, this is due to us adding the order button at a different place within the checkout. We will add some JS to copy the nonce so that we don't have to insert them twice.
