### ISSUE TITLE
Checkout Review and Payment gets restructured

### ISSUE THREAD

**Issue by janmei** [vendidero/woocommerce-germanized#76]
Hey, 

I am currently on Version 1.9.9 of Germanized, and without touching anything in the settings or in the functions.php the checkout page gets completely reordered. The Headlines and the structure just don't make any sense to me.
Even when i tried to fix it myself it broke completely and didn't work at all. 

It currently looks like this 
![bildschirmfoto 2018-04-15 um 21 58 13](https://user-images.githubusercontent.com/2657641/38782782-ce1a8366-40f8-11e8-827a-55598c2d0a90.png)

Why is the Headline on the very end when codewise it is on the very top?

Here is the code part which I am talking about:

`<div class="col-2">
            <h3 id="order_review_heading"><?php _e( "Your order", "woocommerce" ); ?></h3>
              
            <?php do_action( 'woocommerce_checkout_before_order_review' ); ?>
          
            <div id="order_review" class="woocommerce-checkout-review-order">
                <?php do_action( 'woocommerce_checkout_order_review' );?>
            </div>

            <?php do_action( 'woocommerce_checkout_after_order_review' ); ?>
        </div>`

Do you have any suggestions for that? 
I've been struggling with this for quit long now.

Thanks ;)

**Comment by vendidero** [comment]
Hi there,

by default, Germanized tries to switch the payment selection with the items table due to the button solution and a specification from the "Händlerbund". Seems like this process is not really working out with your theme (which could be due to some hooks missing or set at unpredicted places/priorities). Did you try that with a default theme?

**Comment by janmei** [comment]
That explains a lot. Thank you for your quick response :)
