### ISSUE TITLE
On activation customers always get login/registration page during checkout

### ISSUE THREAD

**Issue by Dejo-commerce** [vendidero/woocommerce-germanized#77]
As soon as I activate the plugin on my woocommerce sites, the customers get a login/registration page during checkout even though the login/registration on the checkout page is activated. It's very annoying because I want that my customers get directly to the checkout page.

login/registration page:

![image](https://user-images.githubusercontent.com/39573301/40456511-1291f62a-5ef2-11e8-83cc-012db4b8b450.png)

Woocommerce settings:
![image](https://user-images.githubusercontent.com/39573301/40456437-b6bff8d8-5ef1-11e8-9786-58954cbaf408.png)

**Comment by vendidero** [comment]
Hi there,

that is due to your germanized settings. See the double-opt-in-options within the germanized settings for further details.

Cheers

**Comment by Dejo-commerce** [comment]
Thanks for your support. When I deactivate the double-opt-in, it works as expected. 

Is it possible to have the double-opt-in and the registration on checkout-page at the same time?

**Comment by s-a-s-k-i-a** [comment]
+1 for this question.
This leaves me wondering wether WooCommerce is actually able to assign an already placed order automatically to a specific customer account, once the customer performed the double opt in confirmation click.
Before that, woocommerce should handle the order as guest checkout.

This is probably not implemented out of the box, am I right?

**Comment by vendidero** [comment]
Hi,

thanks for the input - I'm going to check whether we can find some way to work around that problem :)
