### ISSUE TITLE
GDPR - woocommerce account registration - allow shortcodes

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [vendidero/woocommerce-germanized#78]
Hi there!
Could you please either allow shortcode usage in this field:
![dsgvo-germanized](https://user-images.githubusercontent.com/3524165/40536135-74d2d042-600b-11e8-8e91-ea56f25bb9bf.jpg)

OR/AND provide a shortcode permission filter for theme functions.php?

This would come in handy for a wordpress multisite I set up with multiple sites using the same theme, which comes with region settings, where each lets say franchiser can insert their gdpr relevant data such as email, postal address, phone number, etc.
I set up a shortcode which puts out a text which dynamically adapts itself to each franchiser within the network and also makes use of the new gdpr privacy page option that came with wp 4.9.6 ( `get_privacy_policy_url();` ).

Thanks so much!

**Comment by vendidero** [comment]
Hi there,

the text is actually outputted via a template (woocommerce-germanized/myaccount/form-register-checkbox.php). We will furthermore add a filter ("woocommerce_germanized_customer_account_privacy_policy_text") to adjust the text.

Cheers

**Comment by s-a-s-k-i-a** [comment]
In latest version the mentioned template has been removed from plugin core so my adjustment is lst. 
Is the filter in place?

**Comment by s-a-s-k-i-a** [comment]
Found it. I am using this filter now to modify label output of privacy checkbox in registration page:
woocommerce_gzd_legal_checkbox_privacy_label
