### ISSUE TITLE
Compatibility Woocommerce Dynamic Pricing

### ISSUE THREAD

**Issue by mariusmateoc** [vendidero/woocommerce-germanized#82]
In WooCommerce dynamic pricing, I've created a role-based discount of 10%.

On shop page unit price range is not showing the actual discounted price, see the image:
![screen shot 2018-06-28 at 13 24 03](https://user-images.githubusercontent.com/2094443/42031559-ef2c0ada-7ad6-11e8-9c2e-2a8c0c8785c4.png)

Also on the product page (tried variable product only), the unit price is not showing the discounted price but the regular unit price, the same when you change the variation that has another unit price, unit price in not recalculated based on discounted price.
![screen shot 2018-06-28 at 13 22 45](https://user-images.githubusercontent.com/2094443/42031796-daa2182e-7ad7-11e8-8de4-404da12752d0.png)

On cart page and checkout page the unit price is correct but on mini-cart doesn't work and it shows regular unit price

**Comment by vendidero** [comment]
Hi,

are you using the official WooCommerce Dynamic Pricing Plugin? Which plugin version have you been testing? I've been successfully testing v 3.0.9 with our current version. Could you provide us with a screenshot of your dynamic pricing groups for the specific product? 

Cheers

**Comment by mariusmateoc** [comment]
Hi,

Sorry for not providing more information.

I want to create compatibility with [WooCommerce Wholesale Pricing](https://wordpress.org/plugins/woocommerce-wholesale-prices/) and since that is based on role-based pricing after some failed implementations I want to see if Woocommerce Dynamic Pricing is working.

I'm using the [Woocommerce Dynamic Pricing](https://github.com/wp-premium/woocommerce-dynamic-pricing) and the version is 3.1.6 with Germanized v2.0.4. 

I've made a discount to customer role for testing purpose.
![screen shot 2018-07-02 at 08 31 50](https://user-images.githubusercontent.com/2094443/42148825-f4c8d388-7dd3-11e8-8241-a9982e4ac4ae.png)

**Comment by vendidero** [comment]
Hi,

thanks for the feedback. I've checked that and added a commit ensuring better compatibility for variable prices and products in general.

Cheers

**Comment by mariusmateoc** [comment]
Now products and single product page seem to work just fine, but on the mini cart (when hover in the navbar) it shows the old price.

Don't know if this is the right way to fix it but if I add the following line in `class-wc-gzd-compatibility-woocommerce-dynamic-pricing.php`, it shows the right price in mini-cart too.

```php
add_action( 'woocommerce_before_mini_cart', array( $this, 'set_unit_price_filter' ), 10 );
```

P.S. I want to implement another integration with [WooCommerce Wholesale Prices](https://wordpress.org/plugins/woocommerce-wholesale-prices/) and want to know if you could point me to some best practice on how to create that without modifying the plugin or let me know if you would accept a pull request with that integration if I can make it work. Still I'm new to PHP world.

Thanks

**Comment by vendidero** [comment]
Hi there,

yes, that makes sense. I'm going to add that to the compatibility script. Generally you might add your own compatibility script via our filter "woocommerce_gzd_compatibilities". You may of course create your implementation (e.g. based on our compatibility scripts in woocommerce-germanized/includes/compatibility) and create a pull request with your changes.. 

Thanks for helping!

Cheers

**Comment by mariusmateoc** [comment]
Hi,

@vendidero I've started to create compatibility with [WooCommerce Wholesale Pricing](https://wordpress.org/plugins/woocommerce-wholesale-prices/) but I'm stuck at the same problem that Woocommerce Dynamic Pricing had which is with variable products and unit price, works on the cart, checkout, mini-cart but not showing right on shop page and single product page.

I've tried for a couple of hours now to fix it but don't understand how `variable_unit_prices_hash` function works and didn't find an alternative for `on_woocommerce_get_variation_prices_hash` in the WooCommerce Wholesale Pricing plugin codebase.

I could open a PR with that partial integration if you want or you can check the fork [WooCommerce Germanized](https://github.com/mariusmateoc/woocommerce-germanized/tree/compatibility-woocommerce-wholesale-prices).

Sorry for not being able to complete that integration but my PHP, WordPress and WooCommerce knowledge are ... 😞

Cheers
