### ISSUE TITLE
DHL Packstation address format

### ISSUE THREAD

**Issue by suiluj** [vendidero/woocommerce-germanized#83]
Could you please show the address as the following:

Vorname /Name
PostNummer 
**PACKSTATION** + Nummer der DHL PACKSTATION
Postleitzahl und Ort der DHL PACKSTATION, an die die Sendung geleitet werden soll

Lisa Muster
256789
Packstation 123
54321 Musterstadt

The text "Packstation" is missing but is needed as shown here:
https://www.dhl.de/content/dam/dhlde/downloads/pdf/dhl-basisinformationen-zur-adressierung-2011.pdf

**Comment by vendidero** [comment]
Hi there,

the input for that field depends on the user. Some users may want to let packages be sent to a parcel shop instead of a paket box. You may need to inform your user to explicitly insert the actual term.

Cheers

**Comment by suiluj** [comment]
Hi,

ah okay thanks, then i will create a greyed out placeholder as hint for the customer.  
(Perhaps this is option for the plugin settings to change this easily or create presets for the different languages.)
