### ISSUE TITLE
Text: "Please accept the creation of a new customer account" misleading

### ISSUE THREAD

**Issue by jvo-63** [vendidero/woocommerce-germanized#88]
The text is misleading. This should better read "Please accept our privacy policy to create a new customer account".
As well the German translation should read "Bitte akzeptieren Sie unsere Datenschutzerklärung, um ein neues Kundenkonto zu erstellen".

**Comment by vendidero** [comment]
Hi,

thanks for your help. I'm going to change the wording in the next release. Due to this being an option (that may be adjusted by the administrator under WooCommerce > Settings > Germanized > Legal checkboxes), the text will only change for new installations though.

Cheers
