### ISSUE TITLE
Not showing unit price on variable product

### ISSUE THREAD

**Issue by mariusmateoc** [vendidero/woocommerce-germanized#89]
Hi,

Wordpress: 5.1.1
WooCommerce: 3.5.7
WooCommerce Germanized: 2.2.9
WooCommerce Germanized Pro: 1.9.7

I've updated from WooCommerce Germanized 2.2.4 to WooCommerce Germanized 2.2.9, also the wordpress and woocommerce then the unit price on the individual variable product page are strikethrough even if I don't have a sale price or sale unit price set, also on the shop page, cart, etc are showing 0.00$/unit as you can see in the images.

![Screenshot 2019-04-03 at 07 16 09](https://user-images.githubusercontent.com/2094443/55454783-70cd0e00-55e1-11e9-8970-c1f51f1c94ef.png)
![Screenshot 2019-04-03 at 07 13 55](https://user-images.githubusercontent.com/2094443/55454785-70cd0e00-55e1-11e9-8422-20b21037a875.png)
![Screenshot 2019-04-03 at 07 09 27](https://user-images.githubusercontent.com/2094443/55454786-70cd0e00-55e1-11e9-8000-d22359ee1375.png)
![Screenshot 2019-04-03 at 07 09 12](https://user-images.githubusercontent.com/2094443/55454787-70cd0e00-55e1-11e9-8e4d-0d1abf6858c4.png)

**Comment by vendidero** [comment]
Hi there,

hm, that seems strange to me. We've had a little bug with the strikethrough unit prices - could you install our latest master branch and try again? https://github.com/vendidero/woocommerce-germanized/archive/master.zip

The 0,00 unit prices is very odd behaviour as it seems to display correctly on the product page. Are you using some sort of cache? Could you provide us with an URL for testing?

Cheers

**Comment by mariusmateoc** [comment]
Hi,

I use the roots stack and in development env caching on the server is disabled. I manage plugins with composer so to install master branch I add this in my `composer.json` file: 
```
"wpackagist-plugin/woocommerce-germanized": "dev-master as 2.2.x-dev"
```
then I run the `composer update` on the server.

You can access the site here: https://germanized.lightstock.de
* User: germanized
* Password: secret

Also you can access the admin panel: https://germanized.lightstock.de/wp/wp-admin
* User: admin
* Password: admin

Let me know if you need anything.

**Comment by vendidero** [comment]
Hi there,

I've just edited this product: https://germanized.lightstock.de/product/relight-newton-industrieleuchte-aus-emailliertem-stahlblech-matt-schwarz-o-28cm-2m-textilkabel-schwarz/ 

and adjusted a variation unit price to 139 to make sure whether changes are applied (which is the case). I guess you've somehow added products automatically without triggering the manual save functionality? 

Cheers

**Comment by mariusmateoc** [comment]
Yes you're right I'm using [wpallimport](http://www.wpallimport.com/) to add the products, but before didn't have this problem. Also, I've updated their plugin too. 

I've open an issue on wpallimport too and trying to get them here for easy communication and clarify this.

Hope that this will get better support using these plugins together.

**Comment by vendidero** [comment]
Hi there,

the problem is that the save-product-hooks may not be triggered by WP All Import (we are hooking into that event to trigger our unit price recalculation script). Maybe that little snippet for your functions.php might help you out: https://gist.github.com/vendidero/5f14854004133f7a5565d1978b7a26f4

Cheers

**Comment by mariusmateoc** [comment]
Thanks, that snippet fixed my problem.
