### ISSUE TITLE
Revocation form is not working

### ISSUE THREAD

**Issue by robert-budde** [vendidero/woocommerce-germanized#9]
Hi!

Pressing the send-button "Widerruf erklären" does not result in any visible action (neither a validation nor an email). It just simply reloads the revocation form which is empty then. Leaving required fields empty does not trigger any validation error.
Wordpress, Woocommerce and WC GZD are the latest versions, PHP memory is 96M and all other WC functions including emailing are working as expected.

**Comment by vendidero** [comment]
Hi,

please try that with a default theme. I've just tested that myself and it worked like a charm. Maybe this is some kind of Javascript Bug which is produced by some theme/plugin option. The form is being submitted via AJAX.

**Comment by robert-budde** [comment]
Hello!
Thank you for your fast reply. In fact I set up a test website only using the most up-to-date versions of WP, WC and WC GZD. No other plugins are even installed. The theme is the plain one WP comes with. Please check http://projekt131.de/ - the revocation form is right on top. PHP is 5.5. The eMail address is filled in and valid.

**Comment by vendidero** [comment]
Hi,
until now, revocation form does only work on revocation page (the page which has been chosen within GZD settings) - otherwise necessary Javascript won't be loaded. Maybe I'm going to change that behaviour in one of the next releases.

**Comment by robert-budde** [comment]
Thank you, this was the missing hint! It works now. Yet it is somehow confusing, as I want to keep "Widerufsformular / revocation form" and "Widerrufsbelehrung / revocation page" seperate - and the latter one is the one which is set as "revocation page" in WC. If not changed you might want to consider a hint on the "revocation settings page". Thank you!
