### ISSUE TITLE
Add neutral billing title

### ISSUE THREAD

**Issue by Johnny99211** [vendidero/woocommerce-germanized#90]
I currently have the problem that I need a gender neutral billing title in the `set_title_field_mapping_editors`. So maybe it's possible to add a default value like `Please select salutation` which has the default value 0. If you do this, you also need to make this as a required field.

**Comment by vendidero** [comment]
Hi,

you may add additional options via a filter: https://gist.github.com/vendidero/de80a66342893a929d20ee90be70bea3

Cheers
