### ISSUE TITLE
Send customer processing email for SEPA gateway.

### ISSUE THREAD

**Issue by mariusmateoc** [vendidero/woocommerce-germanized#91]
Hi,

I'm using SEPA from Stripe and I want to process those orders before the money transfer. In test mode, the SEPA payment from Stripe is processed immediately and I get the order processing email, but in real life, this can take up to 14days, and I want to send the customer the processing email and mark that order with `woocommerce_germanized_order_email_customer_confirmation_sent` as `true`, so that when the response from stripe came back don't send the user another email.

I thought that if I marked `$order->payment_complete()` this will happened automatically but this isn't the case. What would trigger the processing email if I use an async payment?

```php
add_action( 'wc_gateway_stripe_process_response', 'stripe_sepa_pending_as_complete', 0, 2);
function stripe_sepa_pending_as_complete ($response, $order) {
    if( $response->status === 'pending' && $response->source->type === 'sepa_debit') {
        $order->payment_complete($response->id);
        
        // Stripe don't update the order if not has the status "on-hold"
        $order->add_order_note( sprintf( __( 'Pending Payment status of order automatically set as Payment Complete. The payment may still fail! (Charge ID: %s)' ), $response->id ) );

        if ( is_callable( array( $order, 'save' ) ) ) {
            $order->save();
        }
    }
}


add_filter( 'woocommerce_payment_complete_order_status', 'email_sepa_customer', 10, 2 );
function email_sepa_customer ( $order_status, $order_id ) {

    if ( ! $order_id ) return;
    $order = wc_get_order($order_id); //getting order Object

    if ( $order->get_payment_method() === 'stripe_sepa' ){

        $wc_gzd_email = new WC_GZD_Emails();

        $wc_gzd_email->get_email_instance_by_id( 'customer_processing_order' );
        $wc_gzd_email->trigger_order_confirmation_emails( $order );
        // wc_gzd_send_instant_order_confirmation();

        add_filter( 'woocommerce_germanized_order_email_customer_confirmation_sent', '__return_true' );

        // add_filter( 'woocommerce_gzd_instant_order_confirmation', '__return_false' );

        // add_filter( 'woocommerce_germanized_send_instant_order_confirmation', '__return_true' );
}
```

Based on issue #87 I've tried the following code without success:
```php
add_filter( 'woocommerce_payment_complete', 'email_sepa_customer', 10, 1 );

function email_sepa_customer ( $order_id ) {

    if ( ! $order_id ) return;
    $order = wc_get_order($order_id); //getting order Object

    if ( $order->get_payment_method() === 'stripe_sepa' ) {
        if ( $email = WC_germanized()->emails->get_email_instance_by_id( 'customer_processing_order' ) ) {
            $email->trigger( $order_id );
        } 
    }
}
```

Thanks

**Comment by vendidero** [comment]
Hi there,

normally Germanized sends the order confirmation immediately after submitting the order (no matter which payment method has been chosen). That's why I guess that this is the case for Stripe too. Are the orders submitted via the default WooCommerce checkout?

**Comment by mariusmateoc** [comment]
Hi,

Sorry, my mistake because didn't explain well. I have the order confirmation email disabled since after payment complete I move the order status to `processing` and don't want to send to customers two emails. 

```php
/**
 * Set order status from pending to processing after payment
 */
add_action( 'woocommerce_payment_complete', 'woocommerce_thankyou_change_order_status', 10, 1 );

function woocommerce_thankyou_change_order_status( $order_id ){
    if ( ! $order_id ) return;

    $order = wc_get_order( $order_id );

    if ( $order->get_status() == 'pending' )
        $order->update_status( 'processing' );
}
```

What I want is to send only the `customer_processing_order` email and when the customer pays with Stripe SEPA is an async payment and the customer don't get the `customer_processing_order` email since the payment was not completed and even when I use the following code to mark the order as paid didn't work.

```php
add_action( 'wc_gateway_stripe_process_response', 'stripe_sepa_pending_as_complete', 0, 2);
function stripe_sepa_pending_as_complete ($response, $order) {
    if( $response->status === 'pending' && $response->source->type === 'sepa_debit') {
        $order->payment_complete($response->id);
        
        // Stripe don't update the order if not has the status "on-hold"
        $order->add_order_note( sprintf( __( 'Pending Payment status of order automatically set as Payment Complete. The payment may still fail! (Charge ID: %s)' ), $response->id ) );

        if ( is_callable( array( $order, 'save' ) ) ) {
            $order->save();
        }
    }
}
```

I thought that `customer_processing_order` email will be sent automatically if an order has status processing. How can I send the `customer_processing_order` email manually?

I tried to call [`trigger_order_confirmation_emails`](https://github.com/vendidero/woocommerce-germanized/blob/master/includes/class-wc-gzd-emails.php#L399) function after the order has the processing status but only the admin gets the email and the customer not.

**Comment by vendidero** [comment]
Hi there,

no, the order confirmation email is only triggered once (right after the order has been submitted). We do actually prevent the confirmation being sent when updating the status that's why I guess you don't need to deactivate the processing email. How did you deactivate the email? Within the Woo email settings? In that case programmatically sending the email won't work..

Cheers

**Comment by mariusmateoc** [comment]
Hi,

The problem was on my side, I had disabled the order confirmation email on dev environment and on staging that email was enabled(I was almost sure that is disabled) but I confuse it with order processing email and I thought that client will receive this email when the payment will be completed, after 5 days or so.
 
Sorry I made you waste time on this. 

Thank you and have a nice day
