### ISSUE TITLE
Invoice export with order item (and tax) per line

### ISSUE THREAD

**Issue by sissibieber** [vendidero/woocommerce-germanized#92]
Hello,
since there are enough filters in the invoice export class we are trying to save ourselves some time and extend it, so it is accessible for an accounting software (RZL Import). Now we came across the problem that if there are e.g. 2 products in the order with a different tax class we would need 2 lines per invoice (1 line per product/shipping cost actually). Do you see that happening in the near future? Or do you have another idea for solving this?

Best, Sissi

**Comment by vendidero** [comment]
Hi Sissi,

sorry, I somehow missed that issue :( 

Could you please explain that a little further? You want to extend the invoice export to support multi-lines-per-invoice within the export file? I guess that is somehow not what it is attended to be. Maybe you should consider adding columns instead with the required values?

Cheers
