### ISSUE TITLE
Gutenberg Block-Support?

### ISSUE THREAD

**Issue by nicmare** [vendidero/woocommerce-germanized#97]
Hallo!
Ich habe mich heute mal um die Woocommerce-Blöcke für Gutenberg gekümmert. Dabei habe ich festgestellt, dass sämtliche Kategorie- und Produkt-Blöcke, die Produkte ausgeben, zwar den Preis und den "Add-To-Cart" Button ausgeben aber natürlich nicht die Legals von Germanized – sprich Versandkosten und Steuerangaben. Kann man zeitnah damit rechnen? Schön wäre auch eine Option, statt direkt in den Warenkorb zu legen, auf die Produktseite zu verlinken.
Grüße
Nic

**Comment by vendidero** [comment]
Hi,

für diese Zwecke gibt es aktuell leider nur die Möglichkeit unter Einstellungen > Preisauszeichnung > Widgets & Blöcke Anpassungen vorzunehmen. Leider fehlen noch Filter die Woo zur Verfügung stellen müsste, um da wirklich individuell einzuwirken. Jedenfalls solltest du in den Einstellungen dazu Anpassungen vornehmen können.

Grüße

**Comment by nicmare** [comment]
Du meinst unter "…wp-admin/admin.php?page=wc-settings&tab=germanized&section=display" oder?  Hier habe ich die Checkboxen bei "In Produkt-Widgets" schon gesetzt!

**Comment by vendidero** [comment]
Hi,

du verwendest noch nicht Germanized 3.0 oder? In 3.0 wird das auch für Woo Blöcke hinzugefügt und ist etwas anders strukturiert.

**Comment by nicmare** [comment]
Hey ja das stimmt. Bei Major Releases warte ich lieber ein paar Wochen! Aber gut zu wissen!

**Comment by vendidero** [comment]
Hi,

das ist sicher auch besser so :) Im Zweifel am besten in einer Staging-Umgebung vorab testen. 

Grüße
